import { Link, useSearchParams } from "react-router-dom";
import { BadgeCheck, CalendarClock, Check, ChevronRight, CircleDollarSign, CreditCard, FileText, Gauge, LayoutDashboard, RefreshCw, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import AcademyHeroHeader from "../../components/academy/AcademyHeroHeader.jsx";
import { getAcademyLogoUrl } from "../../utils/fileUrl.js";
import useSubscriptionBilling from "./hooks/useSubscriptionBilling.js";
import { date, joinAddress, money, pretty } from "./subscriptionBilling.utils.js";
import styles from "./SubscriptionBillingHub.module.css";

const TABS = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "plans", label: "Plans", icon: WalletCards }, { id: "payments", label: "Payments", icon: CircleDollarSign }, { id: "invoices", label: "Invoices", icon: FileText }];
const Status = ({ value }) => <span className={`${styles.status} ${styles[value]}`}>{pretty(value)}</span>;
const Usage = ({ label, value = 0, limit, styles: css }) => { const unlimited = limit === undefined || limit === null || Number(limit) < 0; const percent = unlimited ? 0 : Math.min(100, Math.round((Number(value || 0) / Math.max(Number(limit), 1)) * 100)); return <div className={css.usage}><p><strong>{label}</strong><span>{value} / {unlimited ? "Unlimited" : limit}</span></p><i><b style={{ width: `${percent}%` }}/></i></div>; };

const SubscriptionBillingHub = () => {
  const state = useSubscriptionBilling(); const [params, setParams] = useSearchParams(); const requested = params.get("tab") || "overview"; const active = TABS.some((tab) => tab.id === requested) ? requested : "overview"; const branch = state.branches.find((item) => item.isMainBranch) || state.branches[0]; const setTab = (tab) => { const next = new URLSearchParams(params); tab === "overview" ? next.delete("tab") : next.set("tab", tab); setParams(next, { replace: true }); };
  return <div className={`page ${styles.page}`}><AcademyHeroHeader headingId="subscription-academy" academyName={state.academy?.academyName || "KHILADI Academy"} ownerName={state.academy?.ownerName || state.user?.name || "Academy Owner"} logoUrl={state.academy?.logo ? getAcademyLogoUrl(state.academy) : ""} eyebrow="KHILADI subscription" addressLabel={branch?.branchName || "Main Branch"} address={joinAddress(branch) || joinAddress(state.academy) || "Complete billing profile address not available"} summaryItems={[{ key: "plan", icon: ShieldCheck, value: state.plan?.name || "Free", label: "Current Plan" }, { key: "status", icon: BadgeCheck, value: pretty(state.subscription?.status || "active"), label: "Subscription Status" }]} action={<button className={styles.heroAction} type="button" onClick={state.refresh} disabled={state.refreshing}><RefreshCw size={16}/>{state.refreshing ? "Refreshing" : "Refresh"}</button>}/>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><ChevronRight size={13}/><strong>Subscription & Billing</strong></nav><header className={styles.heading}><span><CreditCard size={25}/></span><div><small>Software account</small><h1>Subscription & Billing</h1><p>Manage your KHILADI plan, usage, payments and tax invoices from one secure workspace.</p></div></header><nav className={styles.tabs}>{TABS.map((tab) => { const Icon = tab.icon; return <button type="button" key={tab.id} className={active === tab.id ? styles.activeTab : ""} onClick={() => setTab(tab.id)}><Icon size={17}/>{tab.label}</button>; })}</nav>
    {state.error ? <div className={styles.error}>{state.error}</div> : null}{state.loading ? <div className={styles.loading}><RefreshCw size={27}/><strong>Loading secure billing workspace...</strong></div> : <main>
      {active === "overview" ? <><section className={styles.kpis}><article><span><WalletCards/></span><p><small>Current plan</small><strong>{state.plan?.name || "Free"}</strong><i>{pretty(state.subscription?.billingCycle || state.plan?.billingCycle)}</i></p></article><article><span><CalendarClock/></span><p><small>Valid until</small><strong>{date(state.subscription?.endDate)}</strong><i>{state.stats.daysLeft === null ? "No fixed expiry" : `${state.stats.daysLeft} days remaining`}</i></p></article><article><span><CircleDollarSign/></span><p><small>Total paid</small><strong>{money(state.stats.totalPaid)}</strong><i>{state.stats.paidPayments} successful payments</i></p></article><article><span><FileText/></span><p><small>Invoices</small><strong>{state.stats.invoices}</strong><i>Billing documents</i></p></article></section><section className={styles.grid}><article className={styles.panel}><header><div><small>Subscription</small><h2>Current plan details</h2></div><Status value={state.subscription?.status || "active"}/></header><div className={styles.planSummary}><span><Sparkles size={24}/></span><div><h3>{state.plan?.name || "Free Plan"}</h3><p>{state.plan?.description || "Your current KHILADI Academy Manager subscription."}</p></div><strong>{money(state.plan?.price)}<small>/{state.plan?.billingCycle || "month"}</small></strong></div><dl><div><dt>Started</dt><dd>{date(state.subscription?.startDate)}</dd></div><div><dt>Next billing</dt><dd>{date(state.subscription?.nextBillingDate)}</dd></div><div><dt>Source</dt><dd>{pretty(state.subscription?.source || "free")}</dd></div><div><dt>Plan code</dt><dd>{String(state.subscription?.planCode || state.plan?.code || "free").toUpperCase()}</dd></div></dl><footer><button type="button" onClick={() => setTab("plans")}>Compare plans</button>{["active", "trial"].includes(state.subscription?.status) && state.plan?.code !== "free" ? <button type="button" className={styles.dangerButton} onClick={() => window.confirm("Cancel current subscription?") && state.cancel()}>Cancel subscription</button> : null}</footer></article><article className={styles.panel}><header><div><small>Capacity</small><h2>Plan usage</h2></div><Gauge size={18}/></header><div className={styles.usageList}><Usage styles={styles} label="Students" value={state.usage.students} limit={state.plan?.limits?.students}/><Usage styles={styles} label="Branches" value={state.usage.branches} limit={state.plan?.limits?.branches}/><Usage styles={styles} label="Staff users" value={state.usage.staffUsers || state.usage.users} limit={state.plan?.limits?.staffUsers || state.plan?.limits?.users}/></div></article></section></> : null}
      {active === "plans" ? <section className={styles.planGrid}>{state.plans.map((plan) => { const current = plan.code === (state.subscription?.planCode || state.plan?.code); return <article key={plan._id} className={`${styles.planCard} ${current ? styles.currentPlan : ""}`}><header>{plan.isPopular ? <span>Recommended</span> : <i>{pretty(plan.billingCycle)}</i>}<h2>{plan.name}</h2><p>{plan.description}</p></header><strong>{money(plan.price, plan.currency)}<small>/{plan.billingCycle}</small></strong><ul>{(plan.features || []).map((feature) => <li key={feature}><Check size={14}/>{feature}</li>)}</ul>{current ? <button disabled><BadgeCheck size={16}/>Current plan</button> : <Link to={`/billing/checkout/${plan.code}`}>Choose {plan.name}<ChevronRight size={16}/></Link>}</article>; })}</section> : null}
      {active === "payments" ? <section className={styles.panel}><header><div><small>Transaction audit</small><h2>Subscription Payments</h2><p>KHILADI software subscription payments—not student fee collections.</p></div><b>{state.payments.length} records</b></header><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Plan</th><th>Amount</th><th>Status</th><th>Provider</th><th>Order ID</th><th>Payment ID</th></tr></thead><tbody>{state.payments.map((item) => <tr key={item._id}><td>{date(item.paidAt || item.createdAt)}</td><td><strong>{item.plan?.name || pretty(item.metadata?.planCode)}</strong><small>{pretty(item.plan?.billingCycle)}</small></td><td>{money(item.amount, item.currency)}</td><td><Status value={item.status}/></td><td>{pretty(item.provider)}</td><td>{item.razorpayOrderId || "—"}</td><td>{item.razorpayPaymentId || "—"}</td></tr>)}</tbody></table>{!state.payments.length ? <div className={styles.empty}>No subscription payments found.</div> : null}</div></section> : null}
      {active === "invoices" ? <section className={styles.panel}><header><div><small>Billing documents</small><h2>Invoices</h2><p>View and print issued subscription invoices.</p></div><b>{state.invoices.length} invoices</b></header><div className={styles.tableWrap}><table><thead><tr><th>Invoice</th><th>Issued</th><th>Billing name</th><th>Amount</th><th>Tax</th><th>Total</th><th>Status</th><th/></tr></thead><tbody>{state.invoices.map((item) => <tr key={item._id}><td><strong>{item.invoiceNumber}</strong></td><td>{date(item.issuedAt)}</td><td>{item.billingName || "—"}</td><td>{money(item.amount, item.currency)}</td><td>{money(item.tax, item.currency)}</td><td><strong>{money(item.total, item.currency)}</strong></td><td><Status value={item.status}/></td><td><Link className={styles.viewLink} to={`/billing/invoices/${item._id}`}>View</Link></td></tr>)}</tbody></table>{!state.invoices.length ? <div className={styles.empty}>No invoices generated yet.</div> : null}</div></section> : null}
    </main>}</div>;
};
export default SubscriptionBillingHub;
