import { AlertTriangle, Award, BookOpenCheck, CheckCircle2, ClipboardCheck, Sparkles, TrendingUp, Users } from "lucide-react";
import { categoryMeta, pretty } from "../../pages/skills/skillsStudio.config.js";

const SkillsOverviewPanel = ({ skills, assessments, skillSummary, assessmentSummary, onLibrary, onAssess, styles }) => {
  const published = assessments.filter((item) => (item.status || "published") === "published");
  const uniqueStudents = new Set(published.map((item) => item.student?._id).filter(Boolean)).size;
  const average = published.length ? Math.round(published.reduce((sum, item) => sum + Number(item.percentage ?? (item.score / item.maxScore) * 100), 0) / published.length) : 0;
  const categories = [...new Set(skills.map((skill) => skill.category))].map((category) => { const rows = published.filter((item) => (item.skill?.category || item.skillSnapshot?.category) === category); return { category, count: skills.filter((skill) => skill.category === category).length, average: rows.length ? Math.round(rows.reduce((sum, item) => sum + Number(item.percentage || 0), 0) / rows.length) : 0 }; }).sort((a, b) => b.count - a.count);
  return <div className={styles.overview}><section className={styles.kpis}><article><span className={styles.redIcon}><BookOpenCheck size={21}/></span><div><small>Active Skills</small><strong>{skillSummary.active || skills.length}</strong><p>{skillSummary.categories || categories.length} curriculum categories</p></div></article><article><span className={styles.greenIcon}><Users size={21}/></span><div><small>Students Assessed</small><strong>{uniqueStudents}</strong><p>{published.length} published assessments</p></div></article><article><span className={styles.blueIcon}><TrendingUp size={21}/></span><div><small>Academy Average</small><strong>{average}%</strong><p>Weighted assessment performance</p></div></article><article><span className={styles.purpleIcon}><AlertTriangle size={21}/></span><div><small>Reviews Due</small><strong>{assessmentSummary.dueReviews || 0}</strong><p>{assessmentSummary.drafts || 0} draft assessments</p></div></article></section><section className={styles.overviewGrid}><article className={styles.categoryOverview}><header><div><small>Curriculum coverage</small><h2>Skill Categories</h2></div><button type="button" onClick={onLibrary}>Open Library</button></header><div>{categories.length ? categories.map((item) => { const meta = categoryMeta(item.category); const Icon = meta.icon; return <div key={item.category}><span className={`${styles.categoryIcon} ${styles[`tone${meta.tone[0].toUpperCase()}${meta.tone.slice(1)}`]}`}><Icon size={17}/></span><p><strong>{meta.label}</strong><small>{item.count} skills</small></p><div><i style={{ width: `${item.average}%` }}/></div><b>{item.average ? `${item.average}%` : "Not assessed"}</b></div>; }) : <div className={styles.empty}><Sparkles size={25}/><p>Install the skill catalog to start.</p></div>}</div></article><article className={styles.attention}><header><div><small>Coach priorities</small><h2>Development Focus</h2></div><button type="button" onClick={onAssess}>Assess Student</button></header><div><section><span><ClipboardCheck size={18}/></span><p><strong>{assessmentSummary.drafts || 0} drafts to complete</strong><small>Publish finished assessments so progress is visible.</small></p></section><section><span><Award size={18}/></span><p><strong>{skills.filter((item) => item.isRequired).length} required skills</strong><small>Core skills defined across the academy curriculum.</small></p></section><section><span><CheckCircle2 size={18}/></span><p><strong>{published.length} verified results</strong><small>Historical scores remain available for comparison.</small></p></section></div></article></section></div>;
};

export default SkillsOverviewPanel;
