import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { BadgeCheck, Building2, CreditCard, Eye, ImageUp, Layers3, Save, ShieldCheck, Sparkles, Trash2, Upload } from "lucide-react";
import { academyApi } from "../../api/academyApi.js";
import { getBranches } from "../../api/branchApi.js";
import { idCardTemplateApi } from "../../api/idCardApi.js";
import AcademyHeroHeader from "../../components/academy/AcademyHeroHeader.jsx";
import DocumentStudioSection from "../../components/documentStudio/DocumentStudioSection.jsx";
import FieldPalette from "../../components/documentStudio/FieldPalette.jsx";
import StudioStepRail from "../../components/documentStudio/StudioStepRail.jsx";
import TemplateLibrary from "../../components/documentStudio/TemplateLibrary.jsx";
import IdCardPreview from "../../components/idCards/IdCardPreview.jsx";
import useAuth from "../../hooks/useAuth.js";
import { getAcademyLogoUrl } from "../../utils/fileUrl.js";
import { createTemplateForm, getTemplateSize, ID_CARD_FIELDS, ID_CARD_SIZE_PRESETS, normalizeTemplate, SAMPLE_ID_CARD } from "./idCardTemplate.config.js";
import baseStyles from "./IdCardTemplates.module.css";
import enhancements from "./IdCardEnhancements.module.css";

const styles = { ...baseStyles, ...enhancements };

const steps = [{ id: "identity", label: "Identity", description: "Name and lifecycle" }, { id: "layout", label: "Layout", description: "CR80 and orientation" }, { id: "fields", label: "Fields", description: "Visible card data" }, { id: "branding", label: "Branding", description: "Colour and typography" }, { id: "security", label: "Security", description: "QR and safe area" }, { id: "print", label: "Print", description: "Bleed-ready preview" }];
const payloadOf = (form) => ({ ...form, fields: form.frontDesign.fields });
const multipartPayloadOf = (form, files) => {
  const data = new FormData();
  const payload = payloadOf(form);
  Object.entries(payload).forEach(([key, value]) => {
    data.append(key, ["frontDesign", "backDesign", "customSize", "fields"].includes(key) ? JSON.stringify(value) : String(value ?? ""));
  });
  if (files.front) data.append("frontBackground", files.front);
  if (files.back) data.append("backBackground", files.back);
  return data;
};
const joinAddress = (source) => [source?.address, source?.city, source?.state, source?.country].filter(Boolean).join(", ");

const IdCardTemplates = () => {
  const { user } = useAuth();
  const [templates, setTemplates] = useState([]); const [academy, setAcademy] = useState(null); const [branches, setBranches] = useState([]);
  const [form, setForm] = useState(createTemplateForm); const [editingId, setEditingId] = useState(""); const [activeStep, setActiveStep] = useState("identity"); const [side, setSide] = useState("front"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [backgroundFiles, setBackgroundFiles] = useState({ front: null, back: null }); const [backgroundPreviews, setBackgroundPreviews] = useState({ front: "", back: "" });
  const load = useCallback(async () => { try { setLoading(true); const [templateResult, academyResult, branchResult] = await Promise.allSettled([idCardTemplateApi.getAll(), academyApi.getMyAcademy(), getBranches({ status: "active" })]); if (templateResult.status === "rejected") throw templateResult.reason; setTemplates(templateResult.value?.data?.data?.templates || []); if (academyResult.status === "fulfilled") setAcademy(academyResult.value?.data?.data?.academy || academyResult.value?.data?.academy || null); if (branchResult.status === "fulfilled") { const data = branchResult.value?.data || branchResult.value || []; setBranches(Array.isArray(data) ? data : []); } } catch (error) { toast.error(error?.response?.data?.message || "Templates load nahi ho sake"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const mainBranch = branches.find((item) => item.isMainBranch) || branches[0];
  const previewCard = useMemo(() => ({ ...SAMPLE_ID_CARD, academy: academy || SAMPLE_ID_CARD.academy }), [academy]);
  const update = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));
  const updateDesign = (key, value) => setForm((prev) => ({ ...prev, [side === "front" ? "frontDesign" : "backDesign"]: { ...prev[side === "front" ? "frontDesign" : "backDesign"], [key]: value } }));
  const clearPreviewUrls = () => Object.values(backgroundPreviews).forEach((url) => { if (url) URL.revokeObjectURL(url); });
  const reset = () => { clearPreviewUrls(); setBackgroundFiles({ front: null, back: null }); setBackgroundPreviews({ front: "", back: "" }); setForm(createTemplateForm()); setEditingId(""); setActiveStep("identity"); setSide("front"); };
  const save = async (event) => { event.preventDefault(); try { setSaving(true); const payload = multipartPayloadOf(form, backgroundFiles); if (editingId) await idCardTemplateApi.update(editingId, payload); else await idCardTemplateApi.create(payload); toast.success(editingId ? "Template updated" : "Template created"); reset(); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Template save nahi hua"); } finally { setSaving(false); } };
  const edit = (template) => { clearPreviewUrls(); setBackgroundFiles({ front: null, back: null }); setBackgroundPreviews({ front: "", back: "" }); setForm(normalizeTemplate(template)); setEditingId(template._id); setActiveStep("identity"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const duplicate = async (template) => { try { const copy = normalizeTemplate(template); delete copy._id; delete copy.createdAt; delete copy.updatedAt; await idCardTemplateApi.create({ ...payloadOf(copy), templateName: `${copy.templateName} Copy`, isDefault: false, status: "draft" }); toast.success("Template duplicated"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Duplicate failed"); } };
  const archive = async (template) => { if (!window.confirm(`Archive ${template.templateName}? Existing issued cards remain unchanged.`)) return; try { await idCardTemplateApi.remove(template._id); toast.success("Template archived"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Archive failed"); } };
  const setDefault = async (template) => { try { await idCardTemplateApi.update(template._id, { isDefault: true, status: "published" }); toast.success("Default template updated"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Default update failed"); } };
  const design = side === "front" ? form.frontDesign : form.backDesign;
  const size = getTemplateSize(form);
  const previewTemplate = useMemo(() => ({ ...form, frontDesign: { ...form.frontDesign, backgroundImage: backgroundPreviews.front || form.frontDesign.backgroundImage }, backDesign: { ...form.backDesign, backgroundImage: backgroundPreviews.back || form.backDesign.backgroundImage } }), [backgroundPreviews, form]);
  const chooseBackground = (targetSide, file) => { if (!file) return; if (!file.type.startsWith("image/") || file.size > 2 * 1024 * 1024) return toast.error("Use a JPG, PNG or WEBP image up to 2 MB"); const oldUrl = backgroundPreviews[targetSide]; if (oldUrl) URL.revokeObjectURL(oldUrl); setBackgroundFiles((prev) => ({ ...prev, [targetSide]: file })); setBackgroundPreviews((prev) => ({ ...prev, [targetSide]: URL.createObjectURL(file) })); };
  const removeBackground = (targetSide) => { const oldUrl = backgroundPreviews[targetSide]; if (oldUrl) URL.revokeObjectURL(oldUrl); setBackgroundFiles((prev) => ({ ...prev, [targetSide]: null })); setBackgroundPreviews((prev) => ({ ...prev, [targetSide]: "" })); setForm((prev) => { const key = targetSide === "front" ? "frontDesign" : "backDesign"; return { ...prev, [key]: { ...prev[key], backgroundImage: "" } }; }); };
  return <div className={`page ${styles.page}`}>
    <AcademyHeroHeader headingId="id-template-academy" academyName={academy?.academyName || "KHILADI Academy"} ownerName={academy?.ownerName || user?.name || "Academy Owner"} logoUrl={academy?.logo ? getAcademyLogoUrl(academy) : ""} eyebrow="Identity & document studio" addressLabel={mainBranch?.branchName || "Main Branch"} address={joinAddress(mainBranch) || joinAddress(academy)} summaryItems={[{ key: "templates", icon: Layers3, value: templates.length, label: "Templates" }, { key: "published", icon: BadgeCheck, value: templates.filter((item) => item.status === "published" || item.isDefault).length, label: "Published" }, { key: "format", icon: CreditCard, value: size.label, label: "Card format" }]}/>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><span>/</span><strong>ID Card Template Studio</strong></nav>
    <header className={styles.heading}><div><span><CreditCard/></span><div><small>DOCUMENT DESIGNER</small><h1>ID Card Template Studio</h1><p>Build secure, print-ready student identities with a live front and back preview.</p></div></div><Link to="/id-cards/generate"><Sparkles size={17}/>Generate ID Card</Link></header>
    <form onSubmit={save} className={styles.studio}>
      <aside><StudioStepRail steps={steps} activeStep={activeStep} onChange={setActiveStep}/><div className={styles.versionNote}><ShieldCheck size={17}/><span><strong>Version safe</strong><small>Issued cards keep an immutable snapshot.</small></span></div></aside>
      <div className={styles.controls}>
        {activeStep === "identity" ? <DocumentStudioSection number="1" title="Template Identity" description="Give this reusable design a clear lifecycle."><div className={styles.formGrid}><label>Template Name *<input value={form.templateName} onChange={(e) => update("templateName", e.target.value)} required/></label><label>Status<select value={form.status} onChange={(e) => update("status", e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><label className={styles.check}><input type="checkbox" checked={form.isDefault} onChange={(e) => update("isDefault", e.target.checked)}/>Use as default template</label></div></DocumentStudioSection> : null}
        {activeStep === "layout" ? <DocumentStudioSection number="2" title="Card Layout" description="Choose a standard ID format or enter an exact custom size."><div className={styles.sizePresets}>{ID_CARD_SIZE_PRESETS.map((preset) => <button type="button" key={preset.key} className={form.cardSize === preset.key ? styles.activeSize : ""} onClick={() => update("cardSize", preset.key)}><CreditCard size={18}/><span><strong>{preset.label}</strong><small>{preset.note}</small></span>{form.cardSize === preset.key ? <BadgeCheck size={16}/> : null}</button>)}</div>{form.cardSize === "custom" ? <div className={styles.customSize}><label>Measurement Unit<select value={form.customSize.unit} onChange={(e) => update("customSize", { ...form.customSize, unit: e.target.value })}><option value="cm">Centimetres (cm)</option><option value="in">Inches (in)</option></select></label><label>Width<input type="number" min="1" max="100" step="0.001" value={form.customSize.width} onChange={(e) => update("customSize", { ...form.customSize, width: e.target.value })}/></label><label>Height<input type="number" min="1" max="100" step="0.001" value={form.customSize.height} onChange={(e) => update("customSize", { ...form.customSize, height: e.target.value })}/></label></div> : null}<div className={styles.formGrid}><label>Orientation<select value={form.orientation} onChange={(e) => update("orientation", e.target.value)}><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label><label>Side Label<input value={design.label} onChange={(e) => updateDesign("label", e.target.value)}/></label></div><div className={styles.dimensionNote}><CreditCard size={16}/><span><strong>Print size: {size.widthMm.toFixed(2)} × {size.heightMm.toFixed(2)} mm</strong><small>Orientation and exact dimensions are saved in the issued-card snapshot.</small></span></div></DocumentStudioSection> : null}
        {activeStep === "fields" ? <DocumentStudioSection number="3" title="Visible Fields" description="Choose and reorder the information shown on the selected side."><FieldPalette registry={ID_CARD_FIELDS} selected={design.fields} onChange={(fields) => updateDesign("fields", fields)}/></DocumentStudioSection> : null}
        {activeStep === "branding" ? <DocumentStudioSection number="4" title="Brand System" description="Upload independent front and back artwork, then apply typography and colours."><div className={styles.backgroundUploads}>{["front","back"].map((targetSide) => { const saved = form[targetSide === "front" ? "frontDesign" : "backDesign"].backgroundImage; const preview = backgroundPreviews[targetSide] || saved; return <article key={targetSide}><div>{preview ? <img src={preview.startsWith("blob:") ? preview : `${import.meta.env.VITE_API_URL?.replace(/\/api\/?$/, "") || "http://localhost:5000"}${preview}`} alt={`${targetSide} background`}/> : <ImageUp size={25}/>}</div><span><strong>{targetSide === "front" ? "Front" : "Back"} Background</strong><small>JPG, PNG or WEBP · Maximum 2 MB</small></span><label><Upload size={14}/>Upload<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => chooseBackground(targetSide, e.target.files?.[0])}/></label>{preview ? <button type="button" onClick={() => removeBackground(targetSide)}><Trash2 size={14}/></button> : null}</article>; })}</div><div className={styles.formGrid}><label>Font<select value={form.fontFamily} onChange={(e) => update("fontFamily", e.target.value)}><option>Inter</option><option>Poppins</option><option>Montserrat</option><option>Roboto</option></select></label><label>Photo Shape<select value={form.photoShape} onChange={(e) => update("photoShape", e.target.value)}><option value="circle">Circle</option><option value="rounded">Rounded</option><option value="square">Square</option></select></label>{[["primaryColor","Primary"],["secondaryColor","Secondary"],["accentColor","Accent"],["backgroundColor","Fallback Background"],["textColor","Text"]].map(([key,label]) => <label key={key}>{label} Colour<div className={styles.colorInput}><input type="color" value={form[key]} onChange={(e) => update(key,e.target.value)}/><code>{form[key]}</code></div></label>)}</div></DocumentStudioSection> : null}
        {activeStep === "security" ? <DocumentStudioSection number="5" title="Security & Verification" description="Every issued card receives a signed, revocable QR verification link."><div className={styles.securityBox}><ShieldCheck/><div><strong>Tamper-resistant verification enabled</strong><p>Only a token hash is stored. The public result exposes minimum safe card data.</p></div></div><label className={styles.check}><input type="checkbox" checked={design.showSafeArea} onChange={(e) => updateDesign("showSafeArea", e.target.checked)}/>Show print-safe area</label></DocumentStudioSection> : null}
        {activeStep === "print" ? <DocumentStudioSection number="6" title="Print Production" description="Review safe area and bleed before publishing."><div className={styles.printOptions}><label className={styles.check}><input type="checkbox" checked={design.showBleed} onChange={(e) => updateDesign("showBleed", e.target.checked)}/>Show bleed guide</label><div><strong>{size.label}</strong><span>{size.widthMm.toFixed(2)} × {size.heightMm.toFixed(2)} mm · 300 DPI recommended</span></div></div></DocumentStudioSection> : null}
        <div className={styles.saveBar}><button type="button" onClick={reset}>Reset</button><button type="submit" disabled={saving}><Save size={16}/>{saving ? "Saving..." : editingId ? "Save New Version" : "Save Template"}</button></div>
      </div>
      <section className={styles.previewPane}><header><div><Eye size={16}/><span><strong>Live Preview</strong><small>{size.label} · {form.orientation}</small></span></div><div className={styles.sideTabs}><button type="button" className={side === "front" ? styles.activeTab : ""} onClick={() => setSide("front")}>Front</button><button type="button" className={side === "back" ? styles.activeTab : ""} onClick={() => setSide("back")}>Back</button></div></header><div className={styles.previewStage}><IdCardPreview idCard={previewCard} template={previewTemplate} academy={academy} side={side}/></div><div className={styles.previewMeta}><Building2 size={15}/><span>Live data is sample-only. Generated cards use a frozen student and academy snapshot.</span></div></section>
    </form>
    <TemplateLibrary templates={templates} renderPreview={(template) => <IdCardPreview idCard={previewCard} template={template} academy={academy} compact/>} onEdit={edit} onDuplicate={duplicate} onArchive={archive} onSetDefault={setDefault}/>
    {loading ? <div className={styles.loading}>Loading template library…</div> : null}
  </div>;
};
export default IdCardTemplates;
