import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { Award, BadgeCheck, Eye, FileBadge2, ImageUp, Layers3, Plus, Save, ShieldCheck, Sparkles, Trash2, Upload } from "lucide-react";
import { academyApi } from "../../api/academyApi.js";
import { getBranches } from "../../api/branchApi.js";
import { certificateTemplateApi } from "../../api/certificateApi.js";
import AcademyHeroHeader from "../../components/academy/AcademyHeroHeader.jsx";
import DocumentStudioSection from "../../components/documentStudio/DocumentStudioSection.jsx";
import FieldPalette from "../../components/documentStudio/FieldPalette.jsx";
import StudioStepRail from "../../components/documentStudio/StudioStepRail.jsx";
import TemplateLibrary from "../../components/documentStudio/TemplateLibrary.jsx";
import CertificatePreview from "../../components/certificates/CertificatePreview.jsx";
import useAuth from "../../hooks/useAuth.js";
import { getAcademyLogoUrl, getFileUrl } from "../../utils/fileUrl.js";
import { CERTIFICATE_FIELDS, CERTIFICATE_PAGE_SIZES, CERTIFICATE_TITLE_OPTIONS, CERTIFICATE_TYPES, certificateTitleFor, createCertificateTemplate, getCertificateSize, normalizeCertificateTemplate, SAMPLE_CERTIFICATE } from "./certificateTemplate.config.js";
import baseStyles from "./CertificateTemplates.module.css";
import enhancements from "./CertificateEnhancements.module.css";

const styles = { ...baseStyles, ...enhancements };

const steps = [
  { id: "identity", label: "Identity", description: "Name and lifecycle" },
  { id: "format", label: "Format", description: "Paper size and orientation" },
  { id: "content", label: "Content", description: "Fields and wording" },
  { id: "branding", label: "Branding", description: "Visual system" },
  { id: "signatures", label: "Signatures", description: "Authorization" },
  { id: "security", label: "Security", description: "Verification QR" },
  { id: "print", label: "Print", description: "Safe production" },
];
const joinAddress = (source) => [source?.address, source?.city, source?.state, source?.country].filter(Boolean).join(", ");
const payloadOf = (form) => ({ ...form, fields: form.layoutJson.fields });
const multipartPayloadOf = (form, backgroundFile, signatureFiles) => { const data = new FormData(); Object.entries(payloadOf(form)).forEach(([key, value]) => data.append(key, ["layoutJson", "customPageSize", "fields"].includes(key) ? JSON.stringify(value) : String(value ?? ""))); if (backgroundFile) data.append("certificateBackground", backgroundFile); signatureFiles.forEach((file, index) => { if (file) data.append(`signature${index}`, file); }); return data; };

const CertificateTemplates = () => {
  const { user } = useAuth();
  const [templates, setTemplates] = useState([]); const [academy, setAcademy] = useState(null); const [branches, setBranches] = useState([]);
  const [form, setForm] = useState(createCertificateTemplate); const [editingId, setEditingId] = useState(""); const [activeStep, setActiveStep] = useState("identity"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [backgroundFile, setBackgroundFile] = useState(null); const [backgroundPreview, setBackgroundPreview] = useState(""); const [signatureFiles, setSignatureFiles] = useState([]); const [signaturePreviews, setSignaturePreviews] = useState([]);

  const load = useCallback(async () => { try { setLoading(true); const [templateResult, academyResult, branchResult] = await Promise.allSettled([certificateTemplateApi.getAll(), academyApi.getMyAcademy(), getBranches({ status: "active" })]); if (templateResult.status === "rejected") throw templateResult.reason; setTemplates(templateResult.value?.data?.data?.templates || []); if (academyResult.status === "fulfilled") setAcademy(academyResult.value?.data?.data?.academy || academyResult.value?.data?.academy || null); if (branchResult.status === "fulfilled") { const list = branchResult.value?.data || branchResult.value || []; setBranches(Array.isArray(list) ? list : []); } } catch (error) { toast.error(error?.response?.data?.message || "Certificate templates load nahi ho sake"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const mainBranch = branches.find((item) => item.isMainBranch) || branches[0];
  const preview = useMemo(() => ({ ...SAMPLE_CERTIFICATE, academy: academy || SAMPLE_CERTIFICATE.academy, certificateType: form.certificateType }), [academy, form.certificateType]);
  const update = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));
  const updateLayout = (section, key, value) => setForm((prev) => ({ ...prev, layoutJson: { ...prev.layoutJson, [section]: { ...prev.layoutJson[section], [key]: value } } }));
  const setFields = (fields) => setForm((prev) => ({ ...prev, fields, layoutJson: { ...prev.layoutJson, fields } }));
  const setType = (certificateType) => setForm((prev) => ({ ...prev, certificateType, layoutJson: { ...prev.layoutJson, content: { ...prev.layoutJson.content, title: certificateTitleFor(certificateType) } } }));
  const updateSignature = (index, key, value) => setForm((prev) => ({ ...prev, layoutJson: { ...prev.layoutJson, signatures: prev.layoutJson.signatures.map((signature, signatureIndex) => signatureIndex === index ? { ...signature, [key]: value } : signature) } }));
  const addSignature = () => setForm((prev) => prev.layoutJson.signatures.length >= 6 ? prev : ({ ...prev, layoutJson: { ...prev.layoutJson, signatures: [...prev.layoutJson.signatures, { name: "", role: "", imageUrl: "" }] } }));
  const removeSignature = (index) => { if (form.layoutJson.signatures.length === 1) return; setForm((prev) => ({ ...prev, layoutJson: { ...prev.layoutJson, signatures: prev.layoutJson.signatures.filter((_, itemIndex) => itemIndex !== index) } })); setSignatureFiles((prev) => prev.filter((_, itemIndex) => itemIndex !== index)); setSignaturePreviews((prev) => prev.filter((_, itemIndex) => itemIndex !== index)); };
  const chooseBackground = (file) => { if (!file) return; if (!file.type.startsWith("image/") || file.size > 2 * 1024 * 1024) return toast.error("Use JPG, PNG or WEBP up to 2 MB"); if (backgroundPreview?.startsWith("blob:")) URL.revokeObjectURL(backgroundPreview); setBackgroundFile(file); setBackgroundPreview(URL.createObjectURL(file)); };
  const chooseSignature = (index, file) => { if (!file) return; if (!file.type.startsWith("image/") || file.size > 2 * 1024 * 1024) return toast.error("Use JPG, PNG or WEBP up to 2 MB"); setSignatureFiles((prev) => { const next = [...prev]; next[index] = file; return next; }); setSignaturePreviews((prev) => { const next = [...prev]; if (next[index]?.startsWith("blob:")) URL.revokeObjectURL(next[index]); next[index] = URL.createObjectURL(file); return next; }); };
  const reset = () => { setForm(createCertificateTemplate()); setEditingId(""); setActiveStep("identity"); setBackgroundFile(null); setBackgroundPreview(""); setSignatureFiles([]); setSignaturePreviews([]); };
  const save = async (event) => { event.preventDefault(); try { setSaving(true); const payload = multipartPayloadOf(form, backgroundFile, signatureFiles); if (editingId) await certificateTemplateApi.update(editingId, payload); else await certificateTemplateApi.create(payload); toast.success(editingId ? "New template version saved" : "Certificate template created"); reset(); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Template save nahi hua"); } finally { setSaving(false); } };
  const edit = (template) => { setForm(normalizeCertificateTemplate(template)); setBackgroundFile(null); setBackgroundPreview(""); setSignatureFiles([]); setSignaturePreviews([]); setEditingId(template._id); setActiveStep("identity"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const duplicate = async (template) => { try { const copy = normalizeCertificateTemplate(template); ["_id", "createdAt", "updatedAt", "__v"].forEach((key) => delete copy[key]); await certificateTemplateApi.create({ ...payloadOf(copy), templateName: `${copy.templateName} Copy`, isDefault: false, status: "draft" }); toast.success("Template duplicated"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Duplicate failed"); } };
  const archive = async (template) => { if (!window.confirm(`Archive ${template.templateName}? Issued certificates will remain unchanged.`)) return; try { await certificateTemplateApi.remove(template._id); toast.success("Template archived"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Archive failed"); } };
  const setDefault = async (template) => { try { await certificateTemplateApi.update(template._id, { isDefault: true, status: "published" }); toast.success("Default template updated"); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Default update failed"); } };
  const brand = form.layoutJson.brand; const content = form.layoutJson.content; const print = form.layoutJson.print; const security = form.layoutJson.security;
  const certificateSize = getCertificateSize(form);
  const previewTemplate = useMemo(() => ({ ...form, backgroundImage: backgroundPreview || form.backgroundImage, layoutJson: { ...form.layoutJson, signatures: form.layoutJson.signatures.map((signature, index) => ({ ...signature, imageUrl: signaturePreviews[index] || signature.imageUrl })) } }), [backgroundPreview, form, signaturePreviews]);
  const chooseTitleOption = (option) => setForm((prev) => ({ ...prev, layoutJson: { ...prev.layoutJson, content: { ...prev.layoutJson.content, titleOption: option, title: option === "custom" ? "CERTIFICATE OF " : `CERTIFICATE OF ${option}` } } }));

  return <div className={`page ${styles.page}`}>
    <AcademyHeroHeader headingId="certificate-studio-academy" academyName={academy?.academyName || "KHILADI Academy"} ownerName={academy?.ownerName || user?.name || "Academy Owner"} logoUrl={academy?.logo ? getAcademyLogoUrl(academy) : ""} eyebrow="Certificate & document studio" addressLabel={mainBranch?.branchName || "Main Branch"} address={joinAddress(mainBranch) || joinAddress(academy)} summaryItems={[{ key: "templates", icon: Layers3, value: templates.length, label: "Templates" }, { key: "published", icon: BadgeCheck, value: templates.filter((item) => item.status === "published" || item.isDefault).length, label: "Published" }, { key: "format", icon: FileBadge2, value: form.pageSize === "custom" ? "Custom" : form.pageSize.toUpperCase(), label: form.orientation }]}/>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><span>/</span><strong>Certificate Template Studio</strong></nav>
    <header className={styles.heading}><div><span><Award/></span><div><small>DOCUMENT DESIGNER</small><h1>Certificate Template Studio</h1><p>Create secure, print-ready and verifiable academy certificates.</p></div></div><Link to="/certificates/generate"><Sparkles/>Generate Certificate</Link></header>
    <form className={styles.studio} onSubmit={save}>
      <aside><StudioStepRail steps={steps} activeStep={activeStep} onChange={setActiveStep}/><div className={styles.versionNote}><ShieldCheck/><span><strong>Version safe</strong><small>Issued certificates retain immutable snapshots.</small></span></div></aside>
      <div className={styles.controls}>
        {activeStep === "identity" ? <DocumentStudioSection number="1" title="Template Identity" description="Name, type and publishing lifecycle."><div className={styles.formGrid}><label>Template Name *<input value={form.templateName} onChange={(event) => update("templateName", event.target.value)} required/></label><label>Status<select value={form.status} onChange={(event) => update("status", event.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><div className={styles.full}><span className={styles.label}>Certificate Type</span><div className={styles.typeTags}>{CERTIFICATE_TYPES.map((type) => <button type="button" key={type.value} className={form.certificateType === type.value ? styles.selectedTag : ""} onClick={() => setType(type.value)}>{type.label}</button>)}</div></div><label className={`${styles.check} ${styles.full}`}><input type="checkbox" checked={form.isDefault} onChange={(event) => update("isDefault", event.target.checked)}/>Use as default for this certificate type</label></div></DocumentStudioSection> : null}
        {activeStep === "format" ? <DocumentStudioSection number="2" title="Certificate Format" description="Choose a standard paper format or define an exact custom size."><div className={styles.typeTags}>{CERTIFICATE_PAGE_SIZES.map((size) => <button type="button" key={size.value} className={form.pageSize === size.value ? styles.selectedTag : ""} onClick={() => update("pageSize", size.value)}>{size.label}</button>)}</div>{form.pageSize === "custom" ? <div className={styles.formGrid}><label>Unit<select value={form.customPageSize.unit} onChange={(event) => update("customPageSize", { ...form.customPageSize, unit: event.target.value })}><option value="cm">Centimetres (cm)</option><option value="in">Inches (in)</option></select></label><label>Width<input type="number" min="1" max="200" step="0.01" value={form.customPageSize.width} onChange={(event) => update("customPageSize", { ...form.customPageSize, width: event.target.value })}/></label><label>Height<input type="number" min="1" max="200" step="0.01" value={form.customPageSize.height} onChange={(event) => update("customPageSize", { ...form.customPageSize, height: event.target.value })}/></label></div> : null}<div className={styles.formGrid}><label>Orientation<select value={form.orientation} onChange={(event) => update("orientation", event.target.value)}><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label><label>Exact Print Size<input readOnly value={`${certificateSize.widthMm.toFixed(1)} × ${certificateSize.heightMm.toFixed(1)} mm`}/></label></div><div className={styles.uploadCard}>{backgroundPreview || form.backgroundImage ? <img src={backgroundPreview || getFileUrl(form.backgroundImage)} alt="Certificate background"/> : <ImageUp/>}<span><strong>Certificate Background</strong><small>JPG, PNG or WEBP · Maximum 2 MB</small></span><label><Upload/>Upload Image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => chooseBackground(event.target.files?.[0])}/></label></div></DocumentStudioSection> : null}
        {activeStep === "content" ? <DocumentStudioSection number="3" title="Certificate Content" description="Choose visible fields and professional wording."><FieldPalette registry={CERTIFICATE_FIELDS} selected={form.layoutJson.fields} onChange={setFields}/><span className={styles.label}>Certificate Title · CERTIFICATE OF</span><div className={styles.typeTags}>{CERTIFICATE_TITLE_OPTIONS.map((option) => <button type="button" key={option.value} className={content.titleOption === option.value ? styles.selectedTag : ""} onClick={() => chooseTitleOption(option.value)}>{option.label}</button>)}</div>{content.titleOption === "custom" ? <label className={styles.customTitle}>Custom Certificate Title<input value={content.title.replace(/^CERTIFICATE OF\s*/i, "")} onChange={(event) => updateLayout("content", "title", `CERTIFICATE OF ${event.target.value}`)} placeholder="Enter title"/></label> : null}<div className={styles.formGrid}><label className={styles.full}>Presentation Line<input value={content.eyebrow} onChange={(event) => updateLayout("content", "eyebrow", event.target.value)}/></label><label className={styles.full}>Achievement Statement<textarea rows="4" value={content.statement} onChange={(event) => updateLayout("content", "statement", event.target.value)}/></label></div></DocumentStudioSection> : null}
        {activeStep === "branding" ? <DocumentStudioSection number="4" title="Brand System" description="Academy colours, border and typography."><div className={styles.formGrid}>{[["primaryColor","Primary"],["secondaryColor","Secondary"],["accentColor","Accent"],["backgroundColor","Paper"]].map(([key, label]) => <label key={key}>{label} Colour<div className={styles.colorInput}><input type="color" value={brand[key]} onChange={(event) => updateLayout("brand", key, event.target.value)}/><code>{brand[key]}</code></div></label>)}<label>Heading Font<select value={brand.headingFont} onChange={(event) => updateLayout("brand", "headingFont", event.target.value)}><option>Georgia</option><option>Times New Roman</option><option>Playfair Display</option><option>Montserrat</option></select></label><label>Body Font<select value={brand.bodyFont} onChange={(event) => updateLayout("brand", "bodyFont", event.target.value)}><option>Inter</option><option>Poppins</option><option>Roboto</option><option>Montserrat</option></select></label><label>Border Style<select value={brand.borderStyle} onChange={(event) => updateLayout("brand", "borderStyle", event.target.value)}><option value="heritage">Heritage</option><option value="modern">Modern</option><option value="minimal">Minimal</option></select></label></div></DocumentStudioSection> : null}
        {activeStep === "signatures" ? <DocumentStudioSection number="5" title="Signatures & Authorization" description="Add one to six authorized signatories with uploaded signatures."><div className={styles.signatureGrid}>{form.layoutJson.signatures.map((signature, index) => <article key={index}><span>{String(index + 1).padStart(2, "0")}</span>{form.layoutJson.signatures.length > 1 ? <button type="button" className={styles.removeSignature} onClick={() => removeSignature(index)}><Trash2/></button> : null}<label>Signatory Name<input value={signature.name} onChange={(event) => updateSignature(index, "name", event.target.value)}/></label><label>Designation<input value={signature.role} onChange={(event) => updateSignature(index, "role", event.target.value)}/></label><div className={styles.signatureUpload}>{signaturePreviews[index] || signature.imageUrl ? <img src={signaturePreviews[index] || getFileUrl(signature.imageUrl)} alt="Signature"/> : <Upload/>}<label>Upload Signature<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => chooseSignature(index, event.target.files?.[0])}/></label></div></article>)}</div>{form.layoutJson.signatures.length < 6 ? <button type="button" className={styles.addSignature} onClick={addSignature}><Plus/>Add More Signature</button> : null}<small className={styles.signatureLimit}>{form.layoutJson.signatures.length} of 6 signatures</small></DocumentStudioSection> : null}
        {activeStep === "security" ? <DocumentStudioSection number="6" title="Security & Verification" description="Signed QR verification and tamper-resistant issuance."><div className={styles.securityBox}><ShieldCheck/><div><strong>Secure verification automatically enabled</strong><p>Each issue gets a unique token; only its SHA-256 hash is stored.</p></div></div><label className={styles.check}><input type="checkbox" checked={security.showQr} onChange={(event) => updateLayout("security", "showQr", event.target.checked)}/>Show QR verification</label><label className={styles.check}><input type="checkbox" checked={security.showWatermark} onChange={(event) => updateLayout("security", "showWatermark", event.target.checked)}/>Show academy watermark</label></DocumentStudioSection> : null}
        {activeStep === "print" ? <DocumentStudioSection number="7" title="Print Production" description="Review safe area and bleed before publishing."><div className={styles.printOptions}><label className={styles.check}><input type="checkbox" checked={print.showSafeArea} onChange={(event) => updateLayout("print", "showSafeArea", event.target.checked)}/>Show safe-area guide</label><label className={styles.check}><input type="checkbox" checked={print.showBleed} onChange={(event) => updateLayout("print", "showBleed", event.target.checked)}/>Show bleed guide</label><div><strong>{certificateSize.widthMm.toFixed(1)} × {certificateSize.heightMm.toFixed(1)} mm · {form.orientation}</strong><span>300 DPI recommended · fonts and backgrounds print after preload</span></div></div></DocumentStudioSection> : null}
        <div className={styles.saveBar}><button type="button" onClick={reset}>Reset</button><button type="submit" disabled={saving}><Save/>{saving ? "Saving..." : editingId ? "Save New Version" : "Save Template"}</button></div>
      </div>
      <section className={styles.previewPane}><header><div><Eye/><span><strong>Live Preview</strong><small>{certificateSize.widthMm.toFixed(1)} × {certificateSize.heightMm.toFixed(1)} mm · {form.orientation}</small></span></div><span>{form.status}</span></header><div className={styles.previewStage}><CertificatePreview certificate={preview} template={previewTemplate} academy={academy}/></div><footer><ShieldCheck/>Sample data only. Issued documents use immutable student, academy and source snapshots.</footer></section>
    </form>
    <TemplateLibrary templates={templates} renderPreview={(template) => <CertificatePreview certificate={{ ...preview, certificateType: template.certificateType }} template={template} academy={academy} compact/>} onEdit={edit} onDuplicate={duplicate} onArchive={archive} onSetDefault={setDefault}/>
    {loading ? <div className={styles.loading}>Loading certificate library…</div> : null}
  </div>;
};

export default CertificateTemplates;
