import { useEffect, useMemo, useState } from "react";
import DateInput from "../../components/common/DateInput.jsx";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Award, CalendarDays, FileBadge2, Printer, Search, ShieldCheck, Sparkles, Trophy, UserRound } from "lucide-react";
import { academyApi } from "../../api/academyApi.js";
import { beltTestApi } from "../../api/beltTestApi.js";
import { championshipRecordApi } from "../../api/championshipRecordApi.js";
import { certificateApi, certificateTemplateApi } from "../../api/certificateApi.js";
import { studentApi } from "../../api/studentApi.js";
import CertificatePreview from "../../components/certificates/CertificatePreview.jsx";
import { certificateTitleFor, SAMPLE_CERTIFICATE } from "./certificateTemplate.config.js";
import styles from "./CertificateWorkflow.module.css";

const normalizeList = (response, keys = []) => { const data = response?.data; const candidates = [response, data, data?.data, ...keys.flatMap((key) => [data?.data?.[key], data?.[key], response?.[key]])]; return candidates.find(Array.isArray) || []; };
const studentName = (student) => student?.name || [student?.firstName, student?.lastName].filter(Boolean).join(" ") || "Student";
const studentCode = (student) => student?.admissionNumber || student?.studentCode || "No admission number";
const recordDate = (record) => record?.testDate || record?.startDate || record?.createdAt;
const formatRecordDate = (value) => value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "Date not added";

const GenerateCertificate = () => {
  const navigate = useNavigate();
  const [students, setStudents] = useState([]); const [templates, setTemplates] = useState([]); const [academy, setAcademy] = useState(null); const [beltTests, setBeltTests] = useState([]); const [championships, setChampionships] = useState([]);
  const [query, setQuery] = useState(""); const [generated, setGenerated] = useState(null); const [loading, setLoading] = useState(true); const [recordsLoading, setRecordsLoading] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ student: "", template: "", certificateType: "custom", issueDate: new Date().toISOString().slice(0, 10), relatedBeltTest: "", relatedChampionshipRecord: "", content: { title: "", statement: "", achievement: "", signatoryOneName: "", signatoryOneRole: "", signatoryTwoName: "", signatoryTwoRole: "" } });

  useEffect(() => { Promise.allSettled([certificateTemplateApi.getAll(), academyApi.getMyAcademy()]).then(([templateResult, academyResult]) => { if (templateResult.status === "rejected") throw templateResult.reason; const templateList = normalizeList(templateResult.value, ["templates"]).filter((item) => item.status !== "archived" && !item.isDeleted); setTemplates(templateList); setAcademy(academyResult.status === "fulfilled" ? academyResult.value?.data?.data?.academy || null : null); const selected = templateList.find((item) => item.isDefault) || templateList.find((item) => item.status === "published") || templateList[0]; if (selected) setForm((prev) => ({ ...prev, template: selected._id, certificateType: selected.certificateType, content: { ...prev.content, title: selected.layoutJson?.content?.title || certificateTitleFor(selected.certificateType) } })); }).catch((error) => toast.error(error?.response?.data?.message || "Certificate templates load nahi hue")).finally(() => setLoading(false)); }, []);
  useEffect(() => { const search = query.trim(); if (!search) return undefined; const timer = window.setTimeout(async () => { try { const response = await studentApi.getAll({ limit: 100, search }); const incoming = normalizeList(response, ["students"]); setStudents((current) => { const map = new Map(current.map((student) => [student._id, student])); incoming.forEach((student) => map.set(student._id, student)); return [...map.values()]; }); } catch (error) { toast.error(error?.response?.data?.message || "Students load nahi ho sake"); } }, 250); return () => window.clearTimeout(timer); }, [query]);

  useEffect(() => { if (!form.student) { setBeltTests([]); setChampionships([]); return; } let active = true; setRecordsLoading(true); Promise.allSettled([beltTestApi.getByStudent(form.student), championshipRecordApi.getByStudent(form.student)]).then(([beltResult, championshipResult]) => { if (!active) return; setBeltTests(beltResult.status === "fulfilled" ? normalizeList(beltResult.value, ["beltTests", "records"]) : []); setChampionships(championshipResult.status === "fulfilled" ? normalizeList(championshipResult.value, ["championshipRecords", "records"]) : []); }).finally(() => active && setRecordsLoading(false)); return () => { active = false; }; }, [form.student]);

  const selectedStudent = students.find((item) => item._id === form.student); const selectedTemplate = templates.find((item) => item._id === form.template);
  const filteredStudents = useMemo(() => { const search = query.trim().toLowerCase(); if (!search) return []; return students.filter((item) => [studentName(item), studentCode(item), item.phone, item.batch?.batchName].some((value) => String(value || "").toLowerCase().includes(search))).slice(0, 100); }, [students, query]);
  const sourceRecord = form.relatedBeltTest ? beltTests.find((item) => item._id === form.relatedBeltTest) : form.relatedChampionshipRecord ? championships.find((item) => item._id === form.relatedChampionshipRecord) : null;
  const sourceSnapshot = form.relatedBeltTest && sourceRecord ? { kind: "belt_test", ...sourceRecord } : form.relatedChampionshipRecord && sourceRecord ? { kind: "championship", ...sourceRecord } : { kind: "manual" };
  const preview = generated || { ...SAMPLE_CERTIFICATE, student: selectedStudent || SAMPLE_CERTIFICATE.student, academy: academy || SAMPLE_CERTIFICATE.academy, template: selectedTemplate || {}, certificateType: form.certificateType, issueDate: form.issueDate, contentSnapshot: form.content, sourceSnapshot };
  const chooseTemplate = (templateId) => { const template = templates.find((item) => item._id === templateId); setForm((prev) => ({ ...prev, template: templateId, certificateType: template?.certificateType || "custom", relatedBeltTest: "", relatedChampionshipRecord: "", content: { ...prev.content, title: template?.layoutJson?.content?.title || certificateTitleFor(template?.certificateType) } })); };
  const updateContent = (key, value) => setForm((prev) => ({ ...prev, content: { ...prev.content, [key]: value } }));
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); const payload = { ...form, relatedBeltTest: form.relatedBeltTest || null, relatedChampionshipRecord: form.relatedChampionshipRecord || null }; const response = await certificateApi.generate(payload); const certificate = response.data?.data?.certificate || null; setGenerated(certificate); toast.success("Secure certificate issued"); } catch (error) { toast.error(error?.response?.data?.message || "Certificate generate nahi hua"); } finally { setSaving(false); } };

  return <div className={`page ${styles.page}`}>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><span>/</span><Link to="/certificate-templates">Certificate Studio</Link><span>/</span><strong>Generate</strong></nav>
    <header className={styles.heading}><span><FileBadge2/></span><div><small>SECURE CERTIFICATE ISSUANCE</small><h1>Generate Certificate</h1><p>Select a student, connect an achievement record and issue a verifiable certificate.</p></div></header>
    <div className={styles.workflow}><form className={styles.form} onSubmit={submit}>
      <section><header><span>01</span><div><h2>Student Identity</h2><p>Search active academy students.</p></div></header><label>Search Student *<div className={styles.search}><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, code, phone or batch..."/></div></label><div className={styles.studentResults}>{filteredStudents.map((student) => <button type="button" key={student._id} className={form.student === student._id ? styles.selected : ""} onClick={() => setForm((prev) => ({ ...prev, student: student._id, relatedBeltTest: "", relatedChampionshipRecord: "" }))}><UserRound/><span><strong>{studentName(student)}</strong><small>{studentCode(student)}</small></span>{form.student === student._id ? <ShieldCheck/> : null}</button>)}</div></section>
      <section><header><span>02</span><div><h2>Template & Issue</h2><p>Choose the versioned design and issue date.</p></div></header><div className={styles.twoCol}><label>Template *<select value={form.template} onChange={(event) => chooseTemplate(event.target.value)} required disabled={loading}><option value="">Select template</option>{templates.map((template) => <option key={template._id} value={template._id}>{template.templateName} · v{template.version || 1}{template.isDefault ? " · Default" : ""}</option>)}</select></label><label>Issue Date<div className={styles.date}><CalendarDays/><DateInput value={form.issueDate} onChange={(event) => setForm((prev) => ({ ...prev, issueDate: event.target.value }))}/></div></label></div></section>
      <section><header><span>03</span><div><h2>Achievement Source</h2><p>Verified record data is frozen into the issued certificate.</p></div></header>{form.certificateType === "belt" ? <label>Related Belt Test<select value={form.relatedBeltTest} onChange={(event) => setForm((prev) => ({ ...prev, relatedBeltTest: event.target.value, relatedChampionshipRecord: "" }))} disabled={!form.student || recordsLoading}><option value="">Manual / no linked record</option>{beltTests.map((record) => <option key={record._id} value={record._id}>{record.promotedToBelt}{record.promotedToDanRank ? ` · ${record.promotedToDanRank}` : ""} · {formatRecordDate(recordDate(record))}</option>)}</select></label> : form.certificateType === "championship" ? <label>Related Championship<select value={form.relatedChampionshipRecord} onChange={(event) => setForm((prev) => ({ ...prev, relatedChampionshipRecord: event.target.value, relatedBeltTest: "" }))} disabled={!form.student || recordsLoading}><option value="">Manual / no linked record</option>{championships.map((record) => <option key={record._id} value={record._id}>{record.championshipName} · {record.result} · {formatRecordDate(recordDate(record))}</option>)}</select></label> : <div className={styles.sourceNote}><Trophy/><span><strong>Manual certificate content</strong><small>This certificate type does not require a Belt Test or Championship source.</small></span></div>}</section>
      <section><header><span>04</span><div><h2>Certificate Content</h2><p>Optional values override the template wording for this issue only.</p></div></header><label>Certificate Title<input value={form.content.title} onChange={(event) => updateContent("title", event.target.value)}/></label><label>Achievement / Highlight<input value={form.content.achievement} onChange={(event) => updateContent("achievement", event.target.value)} placeholder="Auto-filled from linked record when empty"/></label><label>Custom Statement<textarea rows="3" value={form.content.statement} onChange={(event) => updateContent("statement", event.target.value)} placeholder="Leave empty to use template statement"/></label></section>
      <button className={styles.primary} type="submit" disabled={saving || !form.student || !form.template}><Sparkles/>{saving ? "Issuing secure certificate..." : "Generate Secure Certificate"}</button>
    </form><aside className={styles.preview}><header><div><Award/><span><strong>Live Certificate Preview</strong><small>A4 · {selectedTemplate?.orientation || "landscape"}</small></span></div>{generated ? <b>ISSUED</b> : <b>PREVIEW</b>}</header><div><CertificatePreview certificate={preview} template={selectedTemplate} academy={academy}/></div>{generated ? <button type="button" onClick={() => navigate(`/certificates/${generated._id}/print`)}><Printer/>Open Print Studio</button> : null}</aside></div>
  </div>;
};

export default GenerateCertificate;
