import express from "express";
import { convertMyEnquiry, deleteMyEnquiry, exportMyEnquiries, getMyEnquiry, getMyEnquiryDashboard, listMyEnquiries, logMyEnquiryCommunication, updateMyEnquiry } from "../controllers/academyEnquiryController.js";
import { protect } from "../middlewares/authMiddleware.js";
import { allowRoles } from "../middlewares/roleMiddleware.js";
const router = express.Router();
router.use(protect, allowRoles("academy_owner", "super_admin"));
router.get("/", listMyEnquiries);
router.get("/dashboard", getMyEnquiryDashboard);
router.get("/export.csv", exportMyEnquiries);
router.get("/:id", getMyEnquiry);
router.patch("/:id", updateMyEnquiry);
router.post("/:id/convert", convertMyEnquiry);
router.post("/:id/communications", logMyEnquiryCommunication);
router.delete("/:id", deleteMyEnquiry);
export default router;
