import express from "express";
import { getPublicAcademy, getPublicAcademySeoIndex, listPublicAcademies } from "../controllers/publicAcademyController.js";
import { createPublicEnquiry } from "../controllers/academyEnquiryController.js";
import { publicEnquiryRateLimiter } from "../middlewares/rateLimiter.js";
const router = express.Router();
router.get("/", listPublicAcademies);
router.get("/seo-index", getPublicAcademySeoIndex);
router.post("/:slug/enquiries", publicEnquiryRateLimiter, createPublicEnquiry);
router.get("/:slug", getPublicAcademy);
export default router;
