import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import admissionEnquiryApi from "../../api/admissionEnquiryApi.js";
import "./AdmissionsEnquiries.css";
import "./AdmissionsWorkflow.css";

const statuses = ["new", "contacted", "trial_scheduled", "trial_completed", "converted", "closed"];
const labels = { new: "New", contacted: "Contacted", trial_scheduled: "Trial scheduled", trial_completed: "Trial completed", converted: "Converted", closed: "Closed" };
const dateValue = (value, withTime = false) => value ? new Date(value).toISOString().slice(0, withTime ? 16 : 10) : "";

export default function AdmissionsEnquiries() {
  const navigate = useNavigate();
  const [items, setItems] = useState([]), [counts, setCounts] = useState({}), [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", status: "", requestType: "" });
  const load = useCallback(async () => { setLoading(true); try { const response = await admissionEnquiryApi.list(filters); setItems(response.data?.data?.items || []); setCounts(response.data?.data?.counts || {}); } catch (error) { toast.error(error.response?.data?.message || "Enquiries load nahi hui"); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const setItem = (id, key, value) => setItems((current) => current.map((item) => item._id === id ? { ...item, [key]: value } : item));
  const save = async (item) => { try { await admissionEnquiryApi.update(item._id, { status: item.status, ownerNotes: item.ownerNotes, priority: item.priority, followUpAt: item.followUpAt || null, trialSchedule: item.trialSchedule }); toast.success("Enquiry updated"); load(); } catch (error) { toast.error(error.response?.data?.message || "Update failed"); } };
  const remove = async (item) => { if (!window.confirm(`${item.name} ki enquiry delete karein?`)) return; try { await admissionEnquiryApi.remove(item._id); toast.success("Enquiry deleted"); load(); } catch (error) { toast.error(error.response?.data?.message || "Delete failed"); } };
  const trial = (item, field, value) => setItem(item._id, "trialSchedule", { ...(item.trialSchedule || {}), [field]: value });
  const exportCsv = async () => { try { const response = await admissionEnquiryApi.exportCsv(); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "academy-enquiries.csv"; link.click(); URL.revokeObjectURL(url); } catch (error) { toast.error(error.response?.data?.message || "Export failed"); } };

  return <div className="admissions-page">
    <header className="admissions-head"><div><h1>Admissions & Enquiries</h1><p>Public leads, trials and follow-ups in one secure pipeline.</p></div><button className="admissions-save" onClick={exportCsv}>Export CSV</button></header>
    <section className="admissions-stats"><div className="admissions-stat"><strong>{counts.new || 0}</strong><span>New leads</span></div><div className="admissions-stat"><strong>{counts.contacted || 0}</strong><span>Contacted</span></div><div className="admissions-stat"><strong>{(counts.trial_scheduled || 0) + (counts.trial_completed || 0)}</strong><span>Trial pipeline</span></div><div className="admissions-stat"><strong>{counts.converted || 0}</strong><span>Converted</span></div></section>
    <section className="admissions-filters"><input className="admissions-input" placeholder="Search name, phone or email" value={filters.search} onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))}/><select className="admissions-input" value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))}><option value="">All statuses</option>{statuses.map((status) => <option value={status} key={status}>{labels[status]}</option>)}</select><select className="admissions-input" value={filters.requestType} onChange={(e) => setFilters((f) => ({ ...f, requestType: e.target.value }))}><option value="">All requests</option><option value="trial_class">Trial class</option><option value="admission">Admission</option><option value="general">General</option></select></section>
    {loading ? <div className="admissions-empty">Loading enquiries…</div> : items.length ? <section className="admissions-list">{items.map((item) =>
      <article className={`admissions-card priority-${item.priority || "normal"}`} key={item._id}>
        <div className="admissions-person"><h3>{item.name}</h3><div>{item.phone}</div>{item.email && <div className="admissions-muted">{item.email}</div>}<span className="admissions-tag">{item.requestType.replace("_", " ")}</span><p className="admissions-muted">Received {new Date(item.createdAt).toLocaleString("en-IN")}</p></div>
        <div className="admissions-details"><p><strong>Age:</strong> {item.studentAge || "—"}</p><p><strong>Program:</strong> {item.martialArt || "Any"}</p><p><strong>Branch:</strong> {item.branchName || "Any"}</p>{item.message && <p><strong>Message:</strong> {item.message}</p>}<div className="admissions-schedule"><label>Follow-up<input className="admissions-input" type="datetime-local" value={dateValue(item.followUpAt, true)} onChange={(e) => setItem(item._id, "followUpAt", e.target.value)}/></label><label>Trial date<input className="admissions-input" type="date" value={dateValue(item.trialSchedule?.date)} onChange={(e) => trial(item, "date", e.target.value)}/></label><label>Start time<input className="admissions-input" type="time" value={item.trialSchedule?.startTime || ""} onChange={(e) => trial(item, "startTime", e.target.value)}/></label><label>End time<input className="admissions-input" type="time" value={item.trialSchedule?.endTime || ""} onChange={(e) => trial(item, "endTime", e.target.value)}/></label></div></div>
        <div className="admissions-actions"><div className="admissions-action-row"><select className="admissions-input" value={item.status} onChange={(e) => setItem(item._id, "status", e.target.value)}>{statuses.map((status) => <option value={status} key={status}>{labels[status]}</option>)}</select><select className="admissions-input" value={item.priority || "normal"} onChange={(e) => setItem(item._id, "priority", e.target.value)}><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option></select></div><textarea className="admissions-input admissions-notes" placeholder="Private follow-up notes" value={item.ownerNotes || ""} onChange={(e) => setItem(item._id, "ownerNotes", e.target.value)} maxLength="1500"/><div className="admissions-buttons"><button className="admissions-detail" onClick={() => navigate(`/admissions/enquiries/${item._id}`)}>Open details</button><button className="admissions-save" onClick={() => save(item)}>Save</button>{item.status !== "converted" && <button className="admissions-convert" onClick={() => navigate("/students/new", { state: { admissionLead: item } })}>Convert to Student</button>}<button className="admissions-delete" onClick={() => remove(item)}>Delete</button></div></div>
      </article>)}</section> : <div className="admissions-empty"><h2>No enquiries found</h2><p>New public enquiries will appear here.</p></div>}
  </div>;
}
