import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { ArrowLeft, ArrowRight, Award, CheckCircle2, Crown, ExternalLink, FileBadge2, GraduationCap, Image, Link2, Medal, RotateCcw, Search, ShieldCheck, Sparkles, Trophy, UserRound, X } from "lucide-react";
import { academyApi } from "../../api/academyApi.js";
import { getBranches } from "../../api/branchApi.js";
import { championshipRecordApi } from "../../api/championshipRecordApi.js";
import { studentApi } from "../../api/studentApi.js";
import AcademyHeroHeader from "../../components/academy/AcademyHeroHeader.jsx";
import { BeltTagsField } from "../../components/common/AcademyOperationsFields.jsx";
import OptionChipsField from "../../components/common/OptionChipsField.jsx";
import PhoneLocationFields from "../../components/common/PhoneLocationFields.jsx";
import { TAEKWONDO_DAN_RANKS } from "../../components/taekwondoBelts/taekwondoBelts.js";
import useAuth from "../../hooks/useAuth.js";
import { getAcademyLogoUrl, getStudentPhotoUrl } from "../../utils/fileUrl.js";
import baseStyles from "./AddChampionshipRecord.module.css";
import enhancementStyles from "./ChampionshipFormEnhancements.module.css";

const styles = { ...baseStyles, ...enhancementStyles };

const TYPES = ["Open", "Official"];
const OFFICIAL_CATEGORIES = ["Association", "Federation", "School Games", "University Games", "National Games"];
const LEVELS = ["District", "Regional", "State", "National", "International"];
const GRADINGS = ["G-1", "G-2", "G-4", "G-8", "G-12", "G-16", "G-20"];
const AGES = ["Sub-Junior", "Cadet", "Junior", "Senior", "Under-14", "Under-17", "Under-19"];
const EVENTS = ["Kyorugi", "Fresher", "Tag Team", "Poomsae"];
const RESULTS = ["Gold", "Silver", "Bronze", "Participation", "Disqualified"];
const BOUT_METHODS = ["Won by Score", "Bye", "Point Gap", "Knockout"];
const EMPTY = { student: "", championshipName: "", championshipType: "Open", officialCategory: "", level: "District", grading: "", sport: "Taekwondo", eventType: "Kyorugi", poomsaeType: "", gender: "Male", ageCategory: "", weightCategory: "", beltCategory: "", danCategory: "", result: "Participation", disqualificationReason: "", ranking: "", totalBouts: "", bouts: [], startDate: "", endDate: "", venue: "", district: "", state: "", country: "India", organizer: "", association: "", certificateUrl: "", medalPhotoUrl: "", matchVideoUrl: "", newsUrl: "", remarks: "" };
const listOf = (r, key) => { const d = r?.data; if (Array.isArray(r)) return r; if (Array.isArray(d)) return d; if (Array.isArray(d?.data)) return d.data; if (Array.isArray(d?.data?.[key])) return d.data[key]; if (Array.isArray(d?.[key])) return d[key]; return []; };
const dataOf = (r) => r?.data?.data || r?.data || r || {};
const nameOf = (s) => s?.name || [s?.firstName, s?.lastName].filter(Boolean).join(" ") || "Student";
const codeOf = (s) => s?.studentCode || s?.admissionNumber || "No admission number";
const addressOf = (v) => [v?.address, v?.city, v?.state, v?.country].map((x) => String(x || "").trim()).filter(Boolean).join(", ");
const dateInput = (v) => { const d = v ? new Date(v) : null; return d && !Number.isNaN(d.getTime()) ? d.toISOString().slice(0, 10) : ""; };
const detectedAge = (s) => { if (s?.ageCategory) return s.ageCategory; const d = new Date(s?.dateOfBirth || s?.dob); if (Number.isNaN(d.getTime())) return ""; const now = new Date(); let age = now.getFullYear() - d.getFullYear(); if (now < new Date(now.getFullYear(), d.getMonth(), d.getDate())) age--; return age <= 11 ? "Sub-Junior" : age <= 14 ? "Cadet" : age <= 17 ? "Junior" : "Senior"; };
const Choice = ({ label, items, value, onChange }) => <OptionChipsField className={styles.championshipTags} label={`${label} *`} multiple={false} options={items} showIcons={false} value={value} onChange={onChange}/>;

const AddChampionshipRecord = ({ editId = "" }) => {
  const navigate = useNavigate(); const [params] = useSearchParams(); const { user } = useAuth(); const isEdit = Boolean(editId);
  const initialStudent = params.get("student") || "";
  const [form, setForm] = useState({ ...EMPTY, student: initialStudent }); const [students, setStudents] = useState([]); const [academy, setAcademy] = useState(null); const [branches, setBranches] = useState([]);
  const [search, setSearch] = useState(""); const [menu, setMenu] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [studentLoadError, setStudentLoadError] = useState(""); const [photo, setPhoto] = useState(false);
  const student = useMemo(() => students.find((s) => String(s._id) === String(form.student)), [students, form.student]);
  const matches = useMemo(() => { const q = search.toLowerCase().trim(); return students.filter((s) => !q || [nameOf(s), codeOf(s), s.phone, s.batch?.batchName].some((v) => String(v || "").toLowerCase().includes(q))).slice(0, 60); }, [students, search]);
  const branch = branches.find((b) => b?.isMainBranch) || branches[0];

  const chooseStudent = (s) => { const gender = String(s.gender || "").toLowerCase(); setSearch(nameOf(s)); setMenu(false); setForm((p) => ({ ...p, student: s._id, sport: s.martialArt || s.batch?.martialArt || p.sport, beltCategory: s.beltRank || p.beltCategory, danCategory: s.beltRank === "Black" ? s.danRank || "" : "", weightCategory: s.weightCategory || p.weightCategory, gender: gender === "male" ? "Male" : gender === "female" ? "Female" : p.gender, ageCategory: detectedAge(s) || p.ageCategory })); };
  useEffect(() => { (async () => { const [sr, ar, br] = await Promise.allSettled([studentApi.getAll({}), academyApi.getMyAcademy(), getBranches({ status: "active" })]); const list = sr.status === "fulfilled" ? listOf(sr.value, "students") : []; setStudents(list); if (ar.status === "fulfilled") setAcademy(dataOf(ar.value).academy || null); if (br.status === "fulfilled") { const value = br.value?.data?.data || br.value?.data || []; setBranches(Array.isArray(value) ? value : []); }
    if (sr.status === "rejected") setStudentLoadError(sr.reason?.response?.data?.message || "Students could not be loaded."); else setStudentLoadError("");
    if (isEdit) try { const response = await championshipRecordApi.getById(editId); const r = response.data?.data?.championshipRecord; setForm({ ...EMPTY, ...r, student: r?.student?._id || r?.student || "", startDate: dateInput(r?.startDate || r?.date), endDate: dateInput(r?.endDate || r?.date), ranking: r?.ranking ?? "", totalBouts: r?.totalBouts || "", bouts: Array.isArray(r?.bouts) ? r.bouts : Array.from({ length: Number(r?.totalBouts || 0) }, (_, i) => ({ boutNumber: i + 1, outcomeMethod: "" })) }); } catch (e) { setError(e.response?.data?.message || "Failed to load championship record"); }
    else if (initialStudent) { const found = list.find((s) => String(s._id) === initialStudent); if (found) chooseStudent(found); } setLoading(false); })(); }, [editId]);
  useEffect(() => { if (student && !search) setSearch(nameOf(student)); }, [student, search]);

  const update = (key, value) => setForm((p) => { const next = { ...p, [key]: value }; if (key === "championshipType" && value !== "Official") { next.officialCategory = ""; next.grading = ""; } if (key === "level" && !(p.championshipType === "Official" && value === "International")) next.grading = ""; if (key === "eventType" && value !== "Poomsae") next.poomsaeType = ""; if (key === "beltCategory" && value !== "Black") next.danCategory = ""; if (key === "result" && value !== "Disqualified") next.disqualificationReason = ""; return next; });
  const change = (e) => update(e.target.name, e.target.value);
  const countBouts = (value) => { const count = Math.max(0, Math.min(50, Number(value || 0))); setForm((p) => ({ ...p, totalBouts: value, bouts: Array.from({ length: count }, (_, i) => p.bouts[i] || { boutNumber: i + 1, outcomeMethod: "" }) })); };
  const locationChange = (key, value) => update(key === "city" ? "district" : key, value);
  const input = (label, key, options = {}) => <label className={options.full ? styles.full : ""}><span>{label}{options.required ? " *" : ""}</span><input type={options.type || "text"} name={key} value={form[key]} onChange={key === "totalBouts" ? (e) => countBouts(e.target.value) : change} required={options.required} min={options.min} max={options.max} maxLength={options.maxLength} placeholder={options.placeholder || ""}/></label>;
  const submit = async (e) => { e.preventDefault(); if (!form.student) return setError("Please select a student."); if (!form.championshipName.trim() || !form.ageCategory || !form.startDate || !form.endDate) return setError("Please complete every required field."); if (form.endDate < form.startDate) return setError("End date cannot be before start date."); if (form.result === "Disqualified" && !form.disqualificationReason.trim()) return setError("Disqualification reason is required."); if (form.bouts.some((b) => !b.outcomeMethod)) return setError("Please select an outcome for every bout."); try { setSaving(true); setError(""); const payload = { ...form, ranking: form.ranking === "" ? null : Number(form.ranking), totalBouts: Number(form.totalBouts || 0), startDate: new Date(`${form.startDate}T00:00:00`).toISOString(), endDate: new Date(`${form.endDate}T00:00:00`).toISOString(), date: new Date(`${form.startDate}T00:00:00`).toISOString() }; if (isEdit) await championshipRecordApi.update(editId, payload); else await championshipRecordApi.create(payload); toast.success(`Championship record ${isEdit ? "updated" : "created"}`); navigate("/championship-records"); } catch (err) { setError(err.response?.data?.message || "Unable to save championship record"); } finally { setSaving(false); } };

  return <div className={`page ${styles.page}`}><AcademyHeroHeader headingId="championship-form-academy" academyName={academy?.academyName || "KHILADI Academy"} ownerName={academy?.ownerName || user?.name || "Academy Owner"} logoUrl={academy?.logo ? getAcademyLogoUrl(academy) : ""} eyebrow="Championship performance desk" addressLabel={branch?.branchName || "Main Branch"} address={addressOf(branch) || addressOf(academy) || "Main branch address not available"} summaryItems={[{ key: "students", icon: GraduationCap, value: students.length, label: "Student Records" }, { key: "results", icon: Medal, value: RESULTS.length, label: "Result Types" }]}/>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><span>/</span><Link to="/championship-records">Championships</Link><span>/</span><strong>{isEdit ? "Edit" : "Add"} Record</strong></nav><header className={styles.heading}><div><span><Trophy size={25}/></span><div><small>Competition achievement</small><h1>{isEdit ? "Edit" : "Add"} Championship Record</h1><p>Record participation, performance, result and official evidence.</p></div></div><Link to="/championship-records"><ArrowLeft size={16}/>Championship Records</Link></header>{error ? <div className={styles.error}><ShieldCheck size={17}/><span>{error}</span><button type="button" onClick={() => setError("")}><X size={15}/></button></div> : null}
    <form className={styles.workspace} onSubmit={submit}><main className={styles.formCard}>
      <section className={styles.section}><header><span>01</span><div><h2>Student Identity</h2><p>Select the athlete and identify the competition.</p></div></header><div className={styles.studentPicker}><label>Search Student *</label><div className={styles.searchBox}><Search size={16}/><input value={search} disabled={loading || isEdit} onChange={(e) => { setSearch(e.target.value); setMenu(true); if (form.student) update("student", ""); }} onFocus={() => setMenu(true)} onBlur={() => setTimeout(() => setMenu(false), 180)} placeholder={loading ? "Loading students..." : "Search name, code, phone or batch..."}/>{student ? <CheckCircle2 size={18}/> : null}</div>{menu && !isEdit && !loading ? <div className={styles.studentMenu}>{studentLoadError ? <p>{studentLoadError}</p> : matches.length ? matches.map((s) => <button key={s._id} type="button" onMouseDown={(e) => e.preventDefault()} onClick={() => chooseStudent(s)}><img src={getStudentPhotoUrl(s)} alt=""/><span><strong>{nameOf(s)}</strong><small>{codeOf(s)}{s.phone ? ` · ${s.phone}` : ""}</small></span><b>{s.batch?.batchName || "No batch"}</b></button>) : <p>{students.length ? "No matching student found." : "No students available in this academy."}</p>}</div> : null}</div>{student ? <article className={styles.studentStrip}><button type="button" onClick={() => setPhoto(true)}><img src={getStudentPhotoUrl(student)} alt={nameOf(student)}/><Image size={14}/></button><div><small>Selected athlete</small><strong>{nameOf(student)}</strong><span>{codeOf(student)}</span></div><dl><div><dt>Batch</dt><dd>{student.batch?.batchName || "Not assigned"}</dd></div><div><dt>Martial Art</dt><dd>{student.martialArt || student.batch?.martialArt || "Not added"}</dd></div><div><dt>Current Belt</dt><dd>{[student.beltRank, student.danRank].filter(Boolean).join(" · ") || "Not added"}</dd></div></dl></article> : null}<div className={styles.grid2}>{input("Championship Name", "championshipName", { required: true, full: true, placeholder: "Official championship name" })}</div></section>
      <section className={styles.section}><header><span>02</span><div><h2>Championship Classification</h2><p>Sport, type and level in one clear row.</p></div></header><div className={styles.classificationRow}>{input("Sport / Martial Art", "sport", { required: true })}<OptionChipsField className={styles.championshipTags} label="Championship Type *" multiple={false} options={TYPES} showIcons={false} value={form.championshipType} onChange={(v) => update("championshipType", v)}/><OptionChipsField className={styles.championshipTags} label="Competition Level *" multiple={false} options={LEVELS} showIcons={false} value={form.level} onChange={(v) => update("level", v)}/></div>{form.championshipType === "Official" ? <div className={styles.grid2}><label><span>Official Category *</span><select name="officialCategory" value={form.officialCategory} onChange={change} required><option value="">Select category</option>{OFFICIAL_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label>{form.level === "International" ? <label><span>International Grading *</span><select name="grading" value={form.grading} onChange={change} required><option value="">Select grading</option>{GRADINGS.map((x) => <option key={x}>{x}</option>)}</select></label> : null}</div> : null}</section>
      <section className={styles.section}><header><span>03</span><div><h2>Competition Division</h2><p>Auto-detected student category can be overridden.</p></div></header><div className={`${styles.divisionRow} ${form.eventType === "Poomsae" ? styles.divisionRowPoomsae : ""}`}><Choice label="Gender" items={["Male", "Female", "Mixed"]} value={form.gender} onChange={(v) => update("gender", v)}/><Choice label="Event Type" items={EVENTS} value={form.eventType} onChange={(v) => update("eventType", v)}/>{form.eventType === "Poomsae" ? <Choice label="Poomsae Type" items={["Individual", "Pair", "Team"]} value={form.poomsaeType} onChange={(v) => update("poomsaeType", v)}/> : null}</div><div className={styles.ageWeightRow}><OptionChipsField className={styles.championshipTags} label="Age Category *" multiple={false} options={AGES} showIcons={false} value={form.ageCategory} onChange={(v) => update("ageCategory", v)}/>{input("Weight Category", "weightCategory", { placeholder: "e.g. Under 58 kg" })}</div><div className={styles.beltDanRow}><BeltTagsField label="Belt Category" value={form.beltCategory} includeNoLimit={false} onChange={(v) => update("beltCategory", form.beltCategory === v ? "" : v)}/>{form.beltCategory === "Black" ? <label className={styles.danCategory}><span>Dan Category</span><select name="danCategory" value={form.danCategory} onChange={change}><option value="">Select Dan</option>{TAEKWONDO_DAN_RANKS.map((dan) => <option key={dan}>{dan}</option>)}</select></label> : null}</div></section>
      <section className={styles.section}><header><span>04</span><div><h2>Result & Performance</h2><p>Final result and winning method for every bout.</p></div></header><div className={styles.resultTopRow}><Choice label="Final Result" items={RESULTS} value={form.result} onChange={(v) => update("result", v)}/><div className={styles.resultBoutCount}>{input("Total Bouts", "totalBouts", { type: "number", min: 0, max: 50 })}<small>Maximum 50 bouts</small></div></div>{form.result === "Disqualified" ? <div className={styles.disqualification}>{input("Disqualification Reason", "disqualificationReason", { required: true, full: true, maxLength: 500, placeholder: "Enter official reason" })}</div> : null}{form.bouts.length ? <div className={styles.boutGrid}>{form.bouts.map((b, i) => <div className={styles.boutMethod} key={i}><OptionChipsField className={styles.championshipTags} label={`Bout ${i + 1} *`} multiple={false} options={BOUT_METHODS} showIcons={false} value={b.outcomeMethod} onChange={(value) => setForm((p) => ({ ...p, bouts: p.bouts.map((x, j) => j === i ? { boutNumber: i + 1, outcomeMethod: value } : x) }))}/></div>)}</div> : <div className={styles.emptyBouts}>Total Bouts enter karne par winning-method tags yahan aayenge.</div>}</section>
      <section className={styles.section}><header><span>05</span><div><h2>Schedule & Location</h2><p>Competition dates, venue and location.</p></div></header><div className={styles.grid2}>{input("Start Date", "startDate", { type: "date", required: true })}{input("End Date", "endDate", { type: "date", required: true })}{input("Venue", "venue", { full: true, placeholder: "Arena, stadium or school" })}</div><div className={styles.locationFields}><PhoneLocationFields showPhone={false} showLocation country={form.country} state={form.state} city={form.district} onChange={locationChange}/></div></section>
      <section className={styles.section}><header><span>06</span><div><h2>Authority & Evidence</h2><p>Useful official links and notes.</p></div></header><div className={styles.grid2}>{input("Organizer", "organizer")}{input("Association / Federation", "association")}</div><div className={styles.linksGrid}>{[["certificateUrl", "Certificate URL", FileBadge2], ["medalPhotoUrl", "Medal Photo URL", Medal], ["matchVideoUrl", "Match Video URL", ExternalLink], ["newsUrl", "News / Coverage URL", Link2]].map(([key, label, Icon]) => <label key={key}><span>{label}</span><div><Icon size={15}/><input type="url" name={key} value={form[key]} onChange={change} placeholder="https://..."/></div></label>)}</div><label className={styles.remarks}><span>Remarks</span><textarea name="remarks" value={form.remarks} onChange={change} rows="4" maxLength="2000"/><small>{form.remarks.length}/2000</small></label></section>
    </main><aside className={styles.review}><header><span><Crown size={20}/></span><div><small>Review & confirm</small><h2>Record Summary</h2></div></header>{student ? <div className={styles.reviewStudent}><img src={getStudentPhotoUrl(student)} alt=""/><div><strong>{nameOf(student)}</strong><span>{codeOf(student)}</span><small>{student.batch?.batchName || "No batch"}</small></div></div> : <div className={styles.reviewEmpty}><UserRound size={25}/><span>Select a student to prepare the record.</span></div>}<div className={`${styles.medalPreview} ${styles[`medal${form.result.replace(/\s/g, "")}`]}`}><Medal size={24}/><div><small>Final Result</small><strong>{form.result}</strong></div></div><dl><div><dt>Championship</dt><dd>{form.championshipName || "Not added"}</dd></div><div><dt>Level</dt><dd>{form.level}</dd></div><div><dt>Event</dt><dd>{form.eventType}</dd></div><div><dt>Division</dt><dd>{[form.ageCategory, form.beltCategory].filter(Boolean).join(" · ") || "Not added"}</dd></div><div><dt>Performance</dt><dd>{form.totalBouts || 0} bouts</dd></div></dl><button className={styles.submit} type="submit" disabled={saving || loading}><Award size={17}/>{saving ? "Saving..." : `${isEdit ? "Update" : "Save"} Record`}<ArrowRight size={16}/></button><button className={styles.reset} type="button" onClick={() => isEdit ? window.location.reload() : setForm({ ...EMPTY, student: initialStudent })}><RotateCcw size={15}/>{isEdit ? "Reload Original" : "Reset Form"}</button><footer><Sparkles size={15}/><span><strong>Achievement timeline</strong>Record will appear in student history and analytics.</span></footer></aside></form>
    {photo && student ? <div className={styles.modal} onClick={() => setPhoto(false)}><div onClick={(e) => e.stopPropagation()}><header><span><small>Student profile</small><h2>{nameOf(student)}</h2><p>{codeOf(student)}</p></span><button type="button" onClick={() => setPhoto(false)}><X size={18}/></button></header><img src={getStudentPhotoUrl(student)} alt={nameOf(student)}/><Link to={`/students/${student._id}`}>View Student Profile<ArrowRight size={15}/></Link></div></div> : null}</div>;
};

export default AddChampionshipRecord;
