import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { City, Country, State } from "country-state-city";
import ReactCountryFlag from "react-country-flag";
import { ArrowLeft, ArrowRight, Award, BadgeCheck, CalendarDays, Check, CheckCircle2, Crown, ExternalLink, FileBadge2, Flag, GraduationCap, Image, Link2, MapPin, Medal, Plus, RotateCcw, Search, ShieldCheck, Sparkles, Trophy, UserRound, X } from "lucide-react";
import { academyApi } from "../../api/academyApi.js";
import { getBranches } from "../../api/branchApi.js";
import { championshipRecordApi } from "../../api/championshipRecordApi.js";
import { studentApi } from "../../api/studentApi.js";
import AcademyHeroHeader from "../../components/academy/AcademyHeroHeader.jsx";
import useAuth from "../../hooks/useAuth.js";
import { getAcademyLogoUrl, getStudentPhotoUrl } from "../../utils/fileUrl.js";
import styles from "./AddChampionshipRecord.module.css";

const TYPES = ["Open", "Official"];
const OFFICIAL_CATEGORIES = ["Association", "Federation", "School Games", "University Games", "National Games"];
const LEVELS = ["District", "Regional", "State", "National", "International"];
const GRADINGS = ["G-1", "G-2", "G-4", "G-8", "G-12", "G-16", "G-20"];
const AGE_CATEGORIES = ["Sub-Junior", "Cadet", "Junior", "Senior", "Under-14", "Under-17", "Under-19"];
const EVENT_TYPES = ["Kyorugi", "Fresher", "Tag Team", "Poomsae"];
const POOMSAE_TYPES = ["Individual", "Pair", "Team"];
const RESULTS = ["Gold", "Silver", "Bronze", "Participation", "No Medal", "Disqualified"];
const initialForm = { student: "", championshipName: "", championshipType: "Open", officialCategory: "", level: "District", grading: "", sport: "Taekwondo", eventType: "Kyorugi", poomsaeType: "", gender: "Male", ageCategory: "", weightCategory: "", beltCategory: "", result: "Participation", ranking: "", totalBouts: "", boutsWon: "", boutsLost: "", pointsScored: "", pointsConceded: "", byeReceived: false, walkoverWin: false, walkoverLoss: false, startDate: "", endDate: "", venue: "", district: "", state: "", country: "India", organizer: "", association: "", registrationNumber: "", sanctionNumber: "", certificateUrl: "", medalPhotoUrl: "", podiumPhotoUrl: "", matchVideoUrl: "", youtubeUrl: "", newsUrl: "", remarks: "" };
const normalizeList = (response, key) => { const data = response?.data; if (Array.isArray(response)) return response; if (Array.isArray(data)) return data; if (Array.isArray(data?.data)) return data.data; if (Array.isArray(data?.data?.[key])) return data.data[key]; if (Array.isArray(data?.[key])) return data[key]; return []; };
const payloadOf = (response) => response?.data?.data || response?.data || response || {};
const studentName = (student) => student?.name || [student?.firstName, student?.lastName].filter(Boolean).join(" ").trim() || "Student";
const studentCode = (student) => student?.studentCode || student?.admissionNumber || "No admission number";
const joinAddress = (value) => [value?.address, value?.city, value?.state, value?.country].map((item) => String(item || "").trim()).filter(Boolean).join(", ");

const ChoiceField = ({ label, items, value, onChange, required = false, className = "" }) => <fieldset className={`${styles.choiceField} ${className}`}><legend>{label}{required ? " *" : ""}</legend><div>{items.map((item) => <button key={item} type="button" className={value === item ? styles.chosen : ""} onClick={() => onChange(value === item && !required ? "" : item)}><span>{item}</span>{value === item ? <Check size={13}/> : null}</button>)}</div></fieldset>;

const AddChampionshipRecord = () => {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { user } = useAuth();
  const studentId = searchParams.get("student") || ""; const countries = useMemo(() => Country.getAllCountries(), []);
  const [form, setForm] = useState({ ...initialForm, student: studentId }); const [students, setStudents] = useState([]); const [academy, setAcademy] = useState(null); const [branches, setBranches] = useState([]);
  const [studentSearch, setStudentSearch] = useState(""); const [studentMenu, setStudentMenu] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showPhoto, setShowPhoto] = useState(false);
  const [countryIso, setCountryIso] = useState("IN"); const [stateIso, setStateIso] = useState("");
  const states = useMemo(() => State.getStatesOfCountry(countryIso), [countryIso]); const districts = useMemo(() => stateIso ? City.getCitiesOfState(countryIso, stateIso) : [], [countryIso, stateIso]);
  const selectedStudent = useMemo(() => students.find((item) => String(item._id) === String(form.student)) || null, [students, form.student]);
  const filteredStudents = useMemo(() => { const query = studentSearch.trim().toLowerCase(); return students.filter((item) => !query || [studentName(item), studentCode(item), item.phone, item.batch?.batchName].some((value) => String(value || "").toLowerCase().includes(query))).slice(0, 60); }, [students, studentSearch]);
  const mainBranch = branches.find((item) => item?.isMainBranch) || branches[0]; const showOfficial = form.championshipType === "Official"; const showGrading = showOfficial && form.level === "International"; const showPoomsae = form.eventType === "Poomsae";
  const winRate = Number(form.totalBouts) > 0 ? Math.round((Number(form.boutsWon || 0) / Number(form.totalBouts)) * 100) : null;

  useEffect(() => { Promise.allSettled([studentApi.getAll({}), academyApi.getMyAcademy(), getBranches({ status: "active" })]).then(([studentResult, academyResult, branchResult]) => { const list = studentResult.status === "fulfilled" ? normalizeList(studentResult.value, "students") : []; setStudents(list); if (academyResult.status === "fulfilled") setAcademy(payloadOf(academyResult.value).academy || null); if (branchResult.status === "fulfilled") { const branchList = branchResult.value?.data?.data || branchResult.value?.data || []; setBranches(Array.isArray(branchList) ? branchList : []); } if (studentId) { const student = list.find((item) => String(item._id) === studentId); if (student) { const normalizedGender = `${student.gender || ""}`.toLowerCase(); setStudentSearch(studentName(student)); setForm((prev) => ({ ...prev, student: studentId, weightCategory: student.weightCategory || "", beltCategory: student.beltRank || "", sport: student.martialArt || student.batch?.martialArt || "Taekwondo", gender: normalizedGender === "male" ? "Male" : normalizedGender === "female" ? "Female" : prev.gender, ageCategory: student.ageCategory || "" })); } } setLoading(false); }); }, [studentId]);

  const update = (name, value) => { if (name === "championshipType") { setForm((prev) => ({ ...prev, championshipType: value, officialCategory: value === "Official" ? prev.officialCategory : "", grading: value === "Official" ? prev.grading : "" })); return; } if (name === "level") { setForm((prev) => ({ ...prev, level: value, grading: prev.championshipType === "Official" && value === "International" ? prev.grading : "" })); return; } if (name === "eventType") { setForm((prev) => ({ ...prev, eventType: value, poomsaeType: value === "Poomsae" ? prev.poomsaeType : "" })); return; } setForm((prev) => ({ ...prev, [name]: value })); };
  const change = (event) => update(event.target.name, event.target.type === "checkbox" ? event.target.checked : event.target.value);
  const chooseStudent = (student) => { setStudentSearch(studentName(student)); setStudentMenu(false); setForm((prev) => ({ ...prev, student: student._id, weightCategory: student.weightCategory || prev.weightCategory, beltCategory: student.beltRank || prev.beltCategory, sport: student.martialArt || student.batch?.martialArt || prev.sport, ageCategory: student.ageCategory || prev.ageCategory })); };
  const searchStudent = (event) => { setStudentSearch(event.target.value); setStudentMenu(true); if (form.student) update("student", ""); };
  const selectCountry = (event) => { const iso = event.target.value; const country = countries.find((item) => item.isoCode === iso); setCountryIso(iso); setStateIso(""); setForm((prev) => ({ ...prev, country: country?.name || "", state: "", district: "" })); };
  const selectState = (event) => { const iso = event.target.value; const state = states.find((item) => item.isoCode === iso); setStateIso(iso); setForm((prev) => ({ ...prev, state: state?.name || "", district: "" })); };
  const reset = () => { setForm({ ...initialForm, student: studentId }); setStudentSearch(studentId && selectedStudent ? studentName(selectedStudent) : ""); setCountryIso("IN"); setStateIso(""); setError(""); };

  const submit = async (event) => { event.preventDefault(); if (!form.student) { setError("Please select a student from search results."); return; } if (!form.championshipName.trim() || !form.ageCategory || !form.startDate || !form.endDate) { setError("Please complete all required championship fields."); return; } if (form.endDate < form.startDate) { setError("End date start date se pehle nahi ho sakti."); return; } if (Number(form.boutsWon || 0) + Number(form.boutsLost || 0) > Number(form.totalBouts || 0)) { setError("Won + Lost bouts total bouts se zyada nahi ho sakte."); return; } try { setSaving(true); setError(""); await championshipRecordApi.create({ ...form, ranking: form.ranking === "" ? null : Number(form.ranking), totalBouts: Number(form.totalBouts || 0), boutsWon: Number(form.boutsWon || 0), boutsLost: Number(form.boutsLost || 0), pointsScored: Number(form.pointsScored || 0), pointsConceded: Number(form.pointsConceded || 0), date: new Date(`${form.startDate}T00:00:00`).toISOString(), startDate: new Date(`${form.startDate}T00:00:00`).toISOString(), endDate: new Date(`${form.endDate}T00:00:00`).toISOString() }); toast.success("Championship record created successfully"); navigate("/championship-records"); } catch (err) { setError(err.response?.data?.message || "Failed to create championship record"); } finally { setSaving(false); } };

  const textField = (label, name, options = {}) => <label className={options.full ? styles.full : ""}><span>{label}{options.required ? " *" : ""}</span><input type={options.type || "text"} name={name} value={form[name]} onChange={change} required={options.required} min={options.min} maxLength={options.maxLength} placeholder={options.placeholder || ""}/></label>;
  return <div className={`page ${styles.page}`}>
    <AcademyHeroHeader headingId="add-championship-academy" academyName={academy?.academyName || "KHILADI Academy"} ownerName={academy?.ownerName || user?.name || "Academy Owner"} logoUrl={academy?.logo ? getAcademyLogoUrl(academy) : ""} eyebrow="Championship performance desk" addressLabel={mainBranch?.branchName || "Main Branch"} address={joinAddress(mainBranch) || joinAddress(academy) || "Complete main branch address not available"} summaryItems={[{ key: "students", icon: GraduationCap, value: students.length, label: "Student Records" }, { key: "result", icon: Medal, value: RESULTS.length, label: "Result Types" }]}/>
    <nav className={styles.breadcrumb}><Link to="/dashboard">Dashboard</Link><span>/</span><Link to="/championship-records">Championships</Link><span>/</span><strong>Add Record</strong></nav>
    <header className={styles.heading}><div><span><Trophy size={25}/></span><div><small>Competition achievement</small><h1>Add Championship Record</h1><p>Record participation, performance, result and official evidence.</p></div></div><Link to="/championship-records"><ArrowLeft size={16}/>Championship Records</Link></header>
    {error ? <div className={styles.error}><ShieldCheck size={17}/><span>{error}</span><button type="button" onClick={() => setError("")}><X size={15}/></button></div> : null}
    <form className={styles.workspace} onSubmit={submit}><main className={styles.formCard}>
      <section className={styles.section}><header><span>01</span><div><h2>Student & Championship</h2><p>Select the athlete and identify the competition.</p></div></header><div className={styles.studentPicker}><label htmlFor="champ-student">Search Student *</label><div className={styles.searchBox}><Search size={16}/><input id="champ-student" value={studentSearch} onChange={searchStudent} onFocus={() => setStudentMenu(true)} onBlur={() => setTimeout(() => setStudentMenu(false),150)} disabled={loading} placeholder={loading ? "Loading students..." : "Search name, code, phone or batch..."}/>{selectedStudent ? <CheckCircle2 size={18}/> : null}</div>{studentMenu && !loading ? <div className={styles.studentMenu}>{filteredStudents.length ? filteredStudents.map((student) => <button key={student._id} type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => chooseStudent(student)}><img src={getStudentPhotoUrl(student)} alt="" onError={(event) => { event.currentTarget.src = "/default-avatar.png"; }}/><span><strong>{studentName(student)}</strong><small>{studentCode(student)}{student.phone ? ` · ${student.phone}` : ""}</small></span><b>{student.batch?.batchName || "No batch"}</b></button>) : <p>No matching student found.</p>}</div> : null}</div>{selectedStudent ? <article className={styles.studentStrip}><button type="button" onClick={() => setShowPhoto(true)}><img src={getStudentPhotoUrl(selectedStudent)} alt={studentName(selectedStudent)} onError={(event) => { event.currentTarget.src = "/default-avatar.png"; }}/><Image size={14}/></button><div><small>Selected athlete</small><strong>{studentName(selectedStudent)}</strong><span>{studentCode(selectedStudent)}</span></div><dl><div><dt>Batch</dt><dd>{selectedStudent.batch?.batchName || "Not assigned"}</dd></div><div><dt>Martial Art</dt><dd>{selectedStudent.martialArt || selectedStudent.batch?.martialArt || "Not added"}</dd></div><div><dt>Current Belt</dt><dd>{selectedStudent.beltRank || "Not added"}</dd></div></dl></article> : null}<div className={styles.grid2}>{textField("Championship Name", "championshipName", { required: true, placeholder: "Official championship name", full: true })}</div></section>
      <section className={styles.section}><header><span>02</span><div><h2>Championship Classification</h2><p>Define competition type, governing category and level.</p></div></header><ChoiceField label="Championship Type" items={TYPES} value={form.championshipType} onChange={(value) => update("championshipType", value)} required/><div className={styles.grid3}>{showOfficial ? <label><span>Official Category *</span><select name="officialCategory" value={form.officialCategory} onChange={change} required><option value="">Select category</option>{OFFICIAL_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label> : null}<label><span>Competition Level *</span><select name="level" value={form.level} onChange={change} required>{LEVELS.map((item) => <option key={item}>{item}</option>)}</select></label>{showGrading ? <label><span>International Grading *</span><select name="grading" value={form.grading} onChange={change} required><option value="">Select grading</option>{GRADINGS.map((item) => <option key={item}>{item}</option>)}</select></label> : null}{textField("Sport / Martial Art", "sport", { placeholder: "Taekwondo" })}</div></section>
      <section className={styles.section}><header><span>03</span><div><h2>Competition Division</h2><p>Record event, gender and competitive category.</p></div></header><ChoiceField label="Event Type" items={EVENT_TYPES} value={form.eventType} onChange={(value) => update("eventType", value)} required/>{showPoomsae ? <ChoiceField label="Poomsae Type" items={POOMSAE_TYPES} value={form.poomsaeType} onChange={(value) => update("poomsaeType", value)} required/> : null}<ChoiceField label="Gender" items={["Male", "Female", "Mixed"]} value={form.gender} onChange={(value) => update("gender", value)} required/><div className={styles.grid3}><label><span>Age Category *</span><select name="ageCategory" value={form.ageCategory} onChange={change} required><option value="">Select age category</option>{AGE_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label>{textField("Weight Category", "weightCategory", { placeholder: "e.g. Under 58 kg" })}{textField("Belt Category", "beltCategory", { placeholder: "e.g. Black Belt" })}</div></section>
      <section className={styles.section}><header><span>04</span><div><h2>Result & Performance</h2><p>Record medal result, fight statistics and special outcomes.</p></div></header><ChoiceField label="Final Result" items={RESULTS} value={form.result} onChange={(value) => update("result", value)} required className={styles.results}/><div className={styles.statsGrid}>{textField("Ranking", "ranking", { type: "number", min: 1, placeholder: "Final rank" })}{textField("Total Bouts", "totalBouts", { type: "number", min: 0 })}{textField("Bouts Won", "boutsWon", { type: "number", min: 0 })}{textField("Bouts Lost", "boutsLost", { type: "number", min: 0 })}{textField("Points Scored", "pointsScored", { type: "number", min: 0 })}{textField("Points Conceded", "pointsConceded", { type: "number", min: 0 })}<div className={styles.winRate}><small>Win Rate</small><strong>{winRate === null ? "—" : `${winRate}%`}</strong></div></div><div className={styles.switches}>{[["byeReceived","Bye Received"],["walkoverWin","Walkover Win"],["walkoverLoss","Walkover Loss"]].map(([name,label]) => <label key={name}><input type="checkbox" name={name} checked={form[name]} onChange={change}/><span/><b>{label}</b></label>)}</div></section>
      <section className={styles.section}><header><span>05</span><div><h2>Schedule & Location</h2><p>Add competition dates, venue and geographic details.</p></div></header><div className={styles.grid2}>{textField("Start Date", "startDate", { type: "date", required: true })}{textField("End Date", "endDate", { type: "date", required: true })}{textField("Venue", "venue", { placeholder: "Arena, stadium or school", full: true })}</div><div className={styles.grid3}><label><span>Country</span><div className={styles.countrySelect}><ReactCountryFlag countryCode={countryIso} svg/><select value={countryIso} onChange={selectCountry}>{countries.map((country) => <option key={country.isoCode} value={country.isoCode}>{country.name}</option>)}</select></div></label><label><span>State</span><select value={stateIso} onChange={selectState}><option value="">Select state</option>{states.map((state) => <option key={state.isoCode} value={state.isoCode}>{state.name}</option>)}</select></label><label><span>District / City</span><select name="district" value={form.district} onChange={change} disabled={!stateIso}><option value="">Select district</option>{districts.map((item) => <option key={`${item.name}-${item.latitude}`} value={item.name}>{item.name}</option>)}</select></label></div></section>
      <section className={styles.section}><header><span>06</span><div><h2>Authority & Evidence</h2><p>Store official references, media links and supporting notes.</p></div></header><div className={styles.grid2}>{textField("Organizer", "organizer", { placeholder: "Organizing body" })}{textField("Association / Federation", "association", { placeholder: "Governing association" })}{textField("Registration Number", "registrationNumber")}{textField("Sanction Number", "sanctionNumber")}</div><div className={styles.linksGrid}>{[["certificateUrl","Certificate URL",FileBadge2],["medalPhotoUrl","Medal Photo URL",Medal],["podiumPhotoUrl","Podium Photo URL",Image],["matchVideoUrl","Match Video URL",ExternalLink],["youtubeUrl","YouTube URL",ExternalLink],["newsUrl","News / Coverage URL",Link2]].map(([name,label,Icon]) => <label key={name}><span>{label}</span><div><Icon size={15}/><input type="url" name={name} value={form[name]} onChange={change} placeholder="https://..."/></div></label>)}</div><label className={styles.remarks}><span>Remarks</span><textarea name="remarks" maxLength="2000" value={form.remarks} onChange={change} rows="4" placeholder="Performance notes, achievements or official observations..."/><small>{form.remarks.length}/2000</small></label></section>
    </main><aside className={styles.review}><header><span><Crown size={20}/></span><div><small>Review & confirm</small><h2>Record Summary</h2></div></header>{selectedStudent ? <div className={styles.reviewStudent}><img src={getStudentPhotoUrl(selectedStudent)} alt="" onError={(event) => { event.currentTarget.src = "/default-avatar.png"; }}/><div><strong>{studentName(selectedStudent)}</strong><span>{studentCode(selectedStudent)}</span><small>{selectedStudent.batch?.batchName || "No batch"}</small></div></div> : <div className={styles.reviewEmpty}><UserRound size={25}/><span>Select a student to prepare the achievement record.</span></div>}<div className={`${styles.medalPreview} ${styles[`medal${form.result.replace(/\s/g,"")}`]}`}><Medal size={24}/><div><small>Final Result</small><strong>{form.result}</strong></div></div><dl><div><dt>Championship</dt><dd>{form.championshipName || "Not added"}</dd></div><div><dt>Level</dt><dd>{form.level}</dd></div><div><dt>Event</dt><dd>{form.eventType}{form.poomsaeType ? ` · ${form.poomsaeType}` : ""}</dd></div><div><dt>Division</dt><dd>{[form.ageCategory,form.weightCategory].filter(Boolean).join(" · ") || "Not added"}</dd></div><div><dt>Dates</dt><dd>{form.startDate || "Not added"}</dd></div><div><dt>Performance</dt><dd>{form.totalBouts || 0} bouts · {form.boutsWon || 0} wins</dd></div></dl><button className={styles.submit} type="submit" disabled={saving || loading}><Award size={17}/>{saving ? "Saving Record..." : "Save Championship Record"}<ArrowRight size={16}/></button><button className={styles.reset} type="button" onClick={reset} disabled={saving}><RotateCcw size={15}/>Reset Form</button><footer><Sparkles size={15}/><span><strong>Achievement timeline</strong>This record will appear in student history and performance analytics.</span></footer></aside></form>
    {showPhoto && selectedStudent ? <div className={styles.modal} onClick={() => setShowPhoto(false)}><div onClick={(event) => event.stopPropagation()}><header><span><small>Student profile</small><h2>{studentName(selectedStudent)}</h2><p>{studentCode(selectedStudent)}</p></span><button type="button" onClick={() => setShowPhoto(false)}><X size={18}/></button></header><img src={getStudentPhotoUrl(selectedStudent)} alt={studentName(selectedStudent)} onError={(event) => { event.currentTarget.src = "/default-avatar.png"; }}/><Link to={`/students/${selectedStudent._id}`}>View Student Profile<ArrowRight size={15}/></Link></div></div> : null}
  </div>;
};
export default AddChampionshipRecord;